### ISSUE TITLE
支持swift吗 

### ISSUE THREAD

**Issue by Michael-lu-ke** [wwmz/WMZPageController#1]

**Comment by wwmz** [comment]
暂时没有swift版本 有时间写个

**Comment by nnianhou-** [comment]
@wwmz 好像Swift调用不了，可以让OC支持一下Swift么，现在项目都是Swift

**Comment by wwmz** [comment]
> @wwmz 好像Swift调用不了，可以让OC支持一下Swift么，现在项目都是Swift

可以用的 直接用属性的方法就可以了
比如self.param.wTitleArr =  [];
这样
