### ISSUE TITLE
打开相册， 照片顶部被导航栏遮盖

### ISSUE THREAD

**Issue by guorenlei** [wwmz/WMZPageController#10]
UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
    imagePicker.delegate = self;
    imagePicker.allowsEditing = YES;
    
    imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
    [self presentViewController:imagePicker animated:YES completion:nil];

**Comment by wwmz** [comment]
> UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
> imagePicker.delegate = self;
> imagePicker.allowsEditing = YES;
> 
> ```
> imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
> [self presentViewController:imagePicker animated:YES completion:nil];
> ```
你在哪里调用这代码啊 我在子控制器调用没啥问题呀

**Comment by guorenlei** [comment]
> > UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
> > imagePicker.delegate = self;
> > imagePicker.allowsEditing = YES;
> > ```
> > imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
> > [self presentViewController:imagePicker animated:YES completion:nil];
> > ```
> 
> 你在哪里调用这代码啊 我在子控制器调用没啥问题呀

在WMZCustomOnePage这个控制器中调用会有问题

**Comment by guorenlei** [comment]
@implementation WMZCustomOnePage
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    __weak WMZCustomOnePage *weakSelf = self;
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    self.navigationController.navigationBar.backgroundColor = [UIColor yellowColor];
    
    UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
    imagePicker.delegate = self;
    imagePicker.allowsEditing = YES;
    //解决照片被导航栏遮挡的偏移问题
    imagePicker.navigationBar.translucent = YES;
    imagePicker.navigationBar.tintColor = [UIColor redColor];
    
    imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
    [self presentViewController:imagePicker animated:YES completion:nil];
    

这样会有问题

**Comment by guorenlei** [comment]
@implementation WMZCustomOnePage
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    __weak WMZCustomOnePage *weakSelf = self;
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    self.navigationController.navigationBar.backgroundColor = [UIColor yellowColor];
    
    UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
    imagePicker.delegate = self;
    imagePicker.allowsEditing = YES;
    
    imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
    [self presentViewController:imagePicker animated:YES completion:nil];

**Comment by guorenlei** [comment]
@implementation WMZCustomOnePage
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    __weak WMZCustomOnePage *weakSelf = self;
    
    self.view.backgroundColor = [UIColor whiteColor];
    
    self.navigationController.navigationBar.backgroundColor = [UIColor yellowColor];
    
    UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
    imagePicker.delegate = self;
    imagePicker.allowsEditing = YES;
    
    imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
    [self presentViewController:imagePicker animated:YES completion:nil];
    

这样调用会有问题， 在我的项目中， 只要显示了这个控制器， push到新的页面， 照片选择的时候顶部图片也是被遮挡。

**Comment by wwmz** [comment]
> @implementation WMZCustomOnePage
> 
> * (void)viewDidLoad {
>   [super viewDidLoad];
>   // Do any additional setup after loading the view.
>   __weak WMZCustomOnePage *weakSelf = self;
>   self.view.backgroundColor = [UIColor whiteColor];
>   self.navigationController.navigationBar.backgroundColor = [UIColor yellowColor];
>   UIImagePickerController *imagePicker = [[UIImagePickerController alloc] init];
>   imagePicker.delegate = self;
>   imagePicker.allowsEditing = YES;
>   imagePicker.sourceType = UIImagePickerControllerSourceTypeSavedPhotosAlbum;
>   [self presentViewController:imagePicker animated:YES completion:nil];
> 
> 这样调用会有问题， 在我的项目中， 只要显示了这个控制器， push到新的页面， 照片选择的时候顶部图片也是被遮挡。

没重现到 你加我q 925457662给我看图吧
