### ISSUE TITLE
请问怎么动态修改某一个标题，给标题添加小红线呢

### ISSUE THREAD

**Issue by xhr4469** [wwmz/WMZPageController#100]
请问怎么动态修改某一个标题，给标题添加小红线呢

**Comment by xhr4469** [comment]
请问怎么动态修改某一个标题，给标题添加小红点或者红色角标呢

**Comment by wwmz** [comment]
> 请问怎么动态修改某一个标题，给标题添加小红点或者红色角标呢

 [self.upSc.btnArr[0] showBadgeWithTopMagin:@{WMZPageKeyBadge:@(10)}];   拿到标题的那个对象执行这个方法

**Comment by xhr4469** [comment]
.wMenuWidthSet([UIScreen mainScreen].bounds.size.width)
//    .wMenuDefaultIndexSet([CoreArchive intForKey:@"answerType"])
    .wMenuDefaultIndexSet(0)
    .wMenuTitleUIFontSet(Font_Medium(15))
    .wMenuTitleSelectUIFontSet(Font_Semibold(17))
    //指示器的宽度
    .wMenuIndicatorWidthSet(ADPW(55))
    //指示器的高度
    .wMenuIndicatorHeightSet(ADPW(3))
    //菜单标题颜色
    .wMenuTitleColorSet([UIColor blackColor])
    //菜单标题选中的颜色
    .wMenuTitleSelectColorSet(DocNavGreenColor)
    //指示器颜色
    .wMenuIndicatorColorSet(DocNavGreenColor)
    .wMenuBgColorSet([UIColor whiteColor])
    .wMenuAnimalSet(PageTitleMenuAiQY)
    .wMenuPositionSet(PageMenuPositionCenter);
//    .wMenuPositionSet(PageMenuPositionNavi);

    param.wMenuTitleWidthSet(PageVCWidth/memu.count);

    self.param = param;

你好，我设置了这些以后。 self.upSc从哪里获取呢？ self.param.upSc.没这个方法呢

**Comment by xhr4469** [comment]
//菜单标题颜色
    .wMenuTitleColorSet([UIColor blackColor])
    //菜单标题选中的颜色
    .wMenuTitleSelectColorSet(DocNavGreenColor)
    //指示器颜色
    .wMenuIndicatorColorSet(DocNavGreenColor)
    .wMenuBgColorSet([UIColor whiteColor])
    .wMenuAnimalSet(PageTitleMenuAiQY)
    .wMenuPositionSet(PageMenuPositionCenter);
//    .wMenuPositionSet(PageMenuPositionNavi);

    param.wMenuTitleWidthSet(PageVCWidth/memu.count);

    self.param = param;

    [self.upSc.btnArr[0] showBadgeWithTopMagin:@{WMZPageKeyBadge:@(10)}];

这样设置了没有效果 哈哈

**Comment by wwmz** [comment]
> //菜单标题颜色 .wMenuTitleColorSet([UIColor blackColor]) //菜单标题选中的颜色 .wMenuTitleSelectColorSet(DocNavGreenColor) //指示器颜色 .wMenuIndicatorColorSet(DocNavGreenColor) .wMenuBgColorSet([UIColor whiteColor]) .wMenuAnimalSet(PageTitleMenuAiQY) .wMenuPositionSet(PageMenuPositionCenter); // .wMenuPositionSet(PageMenuPositionNavi);
> 
> ```
> param.wMenuTitleWidthSet(PageVCWidth/memu.count);
> 
> self.param = param;
> 
> [self.upSc.btnArr[0] showBadgeWithTopMagin:@{WMZPageKeyBadge:@(10)}];
> ```
> 
> 这样设置了没有效果 哈哈
不是实时的要延迟设置 你这时候self.upSc.btnArr是nil  延迟个0.1秒设置即可

**Comment by xhr4469** [comment]
可以了

**Comment by xhr4469** [comment]
非常感谢。
