### ISSUE TITLE
能不能适配一下横竖屏，现在的横竖屏布局太乱了

### ISSUE THREAD

**Issue by zgGitHub** [wwmz/WMZPageController#101]

**Comment by wwmz** [comment]
> _No description provided._

下个版本会更新成自动布局 适配横竖屏

**Comment by weqeo** [comment]
请问有什么办法能强制竖屏吗，我这边设置了强制竖屏，但是我发现只要是继承了WMZPageController的控制器，屏幕宽高还是会按照横屏的来算～～
对了，我这边用的版本因为需要改一些东西，所以是本地代码集成的，没有用pod

更新下，似乎是iOS16+xcode14才会有这个问题

**Comment by wwmz** [comment]
> 请问有什么办法能强制竖屏吗，我这边设置了强制竖屏，但是我发现只要是继承了WMZPageController的控制器，屏幕宽高还是会按照横屏的来算～～ 对了，我这边用的版本因为需要改一些东西，所以是本地代码集成的，没有用pod
> 
> 更新下，似乎是iOS16+xcode14才会有这个问题

 设置wDeviceChange为YES就可以适配横竖屏哦

**Comment by weqeo** [comment]
> 

好的，感谢，我试试～
