### ISSUE TITLE
WMZPageView多重嵌套使用无法左右滑动

### ISSUE THREAD

**Issue by HeiroBoy** [wwmz/WMZPageController#102]
当第二层滑动到最后一个的时候无法滑动到第一层的下一个页面。
请问怎么解决好。

我把demo中的UsePageViewController加了段代码即可复现出来
.wViewControllerSet(^UIViewController * _Nullable(NSInteger index) {
        if (!_iseee) {
            UsePageViewController * vc = UsePageViewController.new;
            vc.iseee = YES;
            return vc;
        }
        return NSClassFromString(@"TopSuspensionVC").new;
    });

**Comment by wwmz** [comment]
> 当第二层滑动到最后一个的时候无法滑动到第一层的下一个页面。 请问怎么解决好。
> 
> 我把demo中的UsePageViewController加了段代码即可复现出来 .wViewControllerSet(^UIViewController * _Nullable(NSInteger index) { if (!_iseee) { UsePageViewController * vc = UsePageViewController.new; vc.iseee = YES; return vc; } return NSClassFromString(@"TopSuspensionVC").new; });

不加就正常？

**Comment by HeiroBoy** [comment]
> 

这是我特地加上去的，原本UsePageViewController只有一层而已

**Comment by HeiroBoy** [comment]
> > 当第二层滑动到最后一个的时候无法滑动到第一层的下一个页面。 请问怎么解决好。
> > 我把demo中的UsePageViewController加了段代码即可复现出来 .wViewControllerSet(^UIViewController * _Nullable(NSInteger index) { if (!_iseee) { UsePageViewController * vc = UsePageViewController.new; vc.iseee = YES; return vc; } return NSClassFromString(@"TopSuspensionVC").new; });
> 
> 不加就正常？

这是我特地加上去的，原本UsePageViewController只有一层而已

**Comment by HeiroBoy** [comment]
demo中绝大多数都是在用WMZPageController，多重嵌套左右滑动没问题。但WMZPageView多重嵌套左右滑动有点问题

**Comment by HeiroBoy** [comment]
在WMZPageLoopView.m中的方法
`- (void)addChildVC:(NSInteger)index VC:(UIResponder*)newReponder`
`if ([parentVC.parentViewController isKindOfClass:[WMZPageController class]]) {
            WMZPageController *parentViewController = (WMZPageController*)parentVC.parentViewController;
            self.dataView.level = parentViewController.upSc.dataView.level - 1;
        }`
        上面判断的是父级是否是WMZPageController，所以导致WMZPageDataView.m中`- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer`判断有误，所以得手动调整WMZPageView对象.upSc.dataView.level的值

**Comment by HeiroBoy** [comment]
目前解决了

**Comment by wwmz** [comment]
> 目前解决了

好的
