### ISSUE TITLE
1.5.5紧急问题(列表白屏)

### ISSUE THREAD

**Issue by XcodeLiubo** [wwmz/WMZPageController#104]
哥们儿，我发现一个问题，如列表页第1项下的的表格共1条数据，左滑到第2项时，第2项的表格上拉加载了二十条后，此时第2项表格的高度肯定是比第1项表格高，滑回到第1项时，此时1项的表格底部大量空白

**Comment by wwmz** [comment]
> 哥们儿，我发现一个问题，如列表页第1项下的的表格共1条数据，左滑到第2项时，第2项的表格上拉加载了二十条后，此时第2项表格的高度肯定是比第1项表格高，滑回到第1项时，此时1项的表格底部大量空白

截个图看看哦

**Comment by XcodeLiubo** [comment]
我还是发你视频

**Comment by XcodeLiubo** [comment]
注意qq

**Comment by wwmz** [comment]
> 我还是发你视频

哦我知道你意思了 这个问题还没修复哦 目前都是固定了一个高度

**Comment by XcodeLiubo** [comment]
那我用哪个版本的

**Comment by wwmz** [comment]
> 那我用哪个版本的

看了视频你的问题好像 不是我以为的那个 你目前用的是WMZPageView还是WMZPageController

**Comment by XcodeLiubo** [comment]
WMZPageController

**Comment by wwmz** [comment]
> WMZPageController

+q说吧

**Comment by XcodeLiubo** [comment]
750506044

**Comment by XcodeLiubo** [comment]
> > WMZPageController
> 
> +q说吧

我加你了, 因为项目要上线, 所以比较急
