### ISSUE TITLE
导航栏适配

### ISSUE THREAD

**Issue by vvunian** [wwmz/WMZPageController#109]
iOS 14和iOS 15导航栏颜色不一样

**Comment by wwmz** [comment]
> iOS 14和iOS 15导航栏颜色不一样

这是你的问题吧。。。这个是控制器层 不是导航栏。。 不会影响你的导航栏的

**Comment by vvunian** [comment]
![WechatIMG272](https://user-images.githubusercontent.com/19220987/218398252-4132a669-a15f-4505-beec-f97927588246.jpeg)

**Comment by wwmz** [comment]
> ![WechatIMG272](https://user-images.githubusercontent.com/19220987/218398252-4132a669-a15f-4505-beec-f97927588246.jpeg)

ios15要适配导航栏的啊 这是你自己代码里要适配的啊 。。。 跟使用这个没关系啊 我demo只是没适配
