### ISSUE TITLE
我项目是自定义导航条的，怎样把你的导航条去掉

### ISSUE THREAD

**Issue by michanMC** [wwmz/WMZPageController#11]

**Comment by wwmz** [comment]
你直接隐藏导航栏就行啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SocialMall <notifications@github.com&gt;
发送时间: 2020年6月10日 15:42
收件人: wwmz/WMZPageController <WMZPageController@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[wwmz/WMZPageController] 我项目是自定义导航条的，怎样把你的导航条去掉 (#11)

**Comment by michanMC** [comment]
我这边项目直接用了FDFullscreenPopGesture 这个库去隐藏导航栏了，但调起WMZPageController 发现并没有去作用，导航栏还在

**Comment by wwmz** [comment]
你这个库我没用过 你试一下原生的会不会出现 如果原生不会的话 就要去我的库里适配一下你这库了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SocialMall <notifications@github.com&gt;
发送时间: 2020年6月10日 16:01
收件人: wwmz/WMZPageController <WMZPageController@noreply.github.com&gt;
抄送: WMZ <925457662@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[wwmz/WMZPageController] 我项目是自定义导航条的，怎样把你的导航条去掉 (#11)





 
我这边项目直接用了FDFullscreenPopGesture 这个库去隐藏导航栏了，但调起WMZPageController 发现并没有去作用，导航栏还在
