### ISSUE TITLE
怎么动态更新HeadView的高度？

### ISSUE THREAD

**Issue by wsjie8283** [wwmz/WMZPageController#110]
headView里的内容更新后需要更新headView高度，怎么更新？

**Comment by wwmz** [comment]
> headView里的内容更新后需要更新headView高度，怎么更新？

updateHeadView

**Comment by wsjie8283** [comment]
> > headView里的内容更新后需要更新headView高度，怎么更新？
> 
> updateHeadView

headView高度更新后，wCustomDataViewHeight再怎么更新呢？controller高度不对了

**Comment by wwmz** [comment]
> headView

headView这个更新不影响wCustomDataViewHeight吧 你这个headView抽一个view手动获取到高度 设置frame 然后去更新

**Comment by wsjie8283** [comment]
> > headView
> 
> headView这个更新不影响wCustomDataViewHeight吧 你这个headView抽一个view手动获取到高度 设置frame 然后去更新

已解决，谢谢

**Comment by wsjie8283** [comment]
需要再调用一下updatePageController
