### ISSUE TITLE
怎么动态刷新菜单栏标题的颜色以及下面的指示器图片，菜单栏中有自定义的标题

### ISSUE THREAD

**Issue by ZJQian** [wwmz/WMZPageController#111]

**Comment by wwmz** [comment]
> _No description provided._

只能拿到指示图那个对象 去动态更改哦

**Comment by ZJQian** [comment]
> > _No description provided._
> 
> 只能拿到指示图那个对象 去动态更改哦

好的谢谢  已经手动导入改源码了😂
