### ISSUE TITLE
如何更新右边固定标题？

### ISSUE THREAD

**Issue by wangyixin** [wwmz/WMZPageController#13]
.wMenuFixRightDataSet(@{@"name":@"金币",@"image":@"f_arrow_upbai"})
    .wEventFixedClickSet(^(id anyID, NSInteger index) {
        WMZPageNaviBtn *btn = anyID;
        [btn setTitle:@"更新" forState:UIControlStateNormal];
    })

是这样更新右边固定标题的吗？这样写页面会变形

**Comment by wwmz** [comment]
> .wMenuFixRightDataSet(@{@"name":@"金币",@"image":@"f_arrow_upbai"})
> .wEventFixedClickSet(^(id anyID, NSInteger index) {
> WMZPageNaviBtn *btn = anyID;
> [btn setTitle:@"更新" forState:UIControlStateNormal];
> })
> 
> 是这样更新右边固定标题的吗？这样写页面会变形

不是这样设置的,重新设置属性 调用更新就行了
self.param.wMenuFixRightDataSet(@{@"name":@"更新",@"image":@"f_arrow_upbai"})
 [self updatePageController];

**Comment by wangyixin** [comment]
WMZPageParam *param = PageParam()
    .wTitleArrSet(@[@"持仓", @"历史"])
    .wMenuTitleColorSet([UIColor grayColor])
    .wControllersSet(@[[FWFuPositionViewController new], [FWFuHistoryViewController new]])
    .wTopSuspensionSet(YES)
    .wScrollCanTransferSet(FALSE)
    .wMenuImagePositionSet(PageBtnPositionRight)
    .wMenuImageMarginSet(8)
    .wMenuFixShadowSet(FALSE)
    .wMenuFixRightDataSet(@{@"name":@"金币",@"image":@"f_arrow_upbai"})
    .wEventFixedClickSet(^(id anyID, NSInteger index) {
        self.param.wMenuFixRightDataSet(@{@"name":@"更新",@"image":@"f_arrow_upbai"});
        [self updatePageController];
    })
我这样设置之后每次点击一下右边按钮，右边按钮都会向左边移动一下。请问是怎么回事

**Comment by wwmz** [comment]
> WMZPageParam *param = PageParam()
> .wTitleArrSet(@[@"持仓", @"历史"])
> .wMenuTitleColorSet([UIColor grayColor])
> .wControllersSet(@[[FWFuPositionViewController new], [FWFuHistoryViewController new]])
> .wTopSuspensionSet(YES)
> .wScrollCanTransferSet(FALSE)
> .wMenuImagePositionSet(PageBtnPositionRight)
> .wMenuImageMarginSet(8)
> .wMenuFixShadowSet(FALSE)
> .wMenuFixRightDataSet(@{@"name":@"金币",@"image":@"f_arrow_upbai"})
> .wEventFixedClickSet(^(id anyID, NSInteger index) {
> self.param.wMenuFixRightDataSet(@{@"name":@"更新",@"image":@"f_arrow_upbai"});
> [self updatePageController];
> })
> 我这样设置之后每次点击一下右边按钮，右边按钮都会向左边移动一下。请问是怎么回事

循环 self.upSc.btnArr 找个tag为10086的按钮 直接更新title即可
