### ISSUE TITLE
titleview  是否可以自定义 attributes string ？

### ISSUE THREAD

**Issue by rgmyyw** [wwmz/WMZPageController#14]
类似这样的

![](https://tva1.sinaimg.cn/large/007S8ZIlgy1ggiitutarkj30dz02xt8k.jpg)

**Comment by wwmz** [comment]
> 类似这样的
> 
> ![](https://camo.githubusercontent.com/5176693fd84ccaecd557cd68b33f30bb77dc4914/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c6779316767696974757461726b6a3330647a30327874386b2e6a7067)
你的gif图打不开哦 
要自定义的话  详情看标题样式里的 index11里的案例 可以自定义的标题的

**Comment by wwmz** [comment]
> 类似这样的
> 
> ![](https://camo.githubusercontent.com/5176693fd84ccaecd557cd68b33f30bb77dc4914/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c6779316767696974757461726b6a3330647a30327874386b2e6a7067)

你的gif图打不开哦
要自定义的话 详情看标题样式里的 index11里的案例 可以自定义的标题的

**Comment by nilhy** [comment]
@wwmz  https://tva1.sinaimg.cn/large/007S8ZIlgy1ggiitutarkj30dz02xt8k.jpg

**Comment by wwmz** [comment]
可以的&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nilhy <notifications@github.com&gt;
发送时间: 2020年7月7日 18:27
收件人: wwmz/WMZPageController <WMZPageController@noreply.github.com&gt;
抄送: WMZ <925457662@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[wwmz/WMZPageController] titleview  是否可以自定义 attributes string ？ (#14)





 
@wwmz  https://tva1.sinaimg.cn/large/007S8ZIlgy1ggiitutarkj30dz02xt8k.jpg

**Comment by nilhy** [comment]
有参考吗？

**Comment by wwmz** [comment]
> 有参考吗？
我加了个示例 你下载最新代码 里面的demoTwo就是

**Comment by wwmz** [comment]
> 有参考吗？

我加了个示例 你下载最新代码 里面的demoTwo就是

**Comment by nilhy** [comment]
您好，之前的问题解决了， 现在我还有一个需求就是，上面的标题数字是需要动态改变的，这能做到吗？

**Comment by nilhy** [comment]
大佬辛苦了，谢谢解答这些问题。不然自己去写，可能真的要被搞死

**Comment by wwmz** [comment]
> 大佬辛苦了，谢谢解答这些问题。不然自己去写，可能真的要被搞死



> 您好，之前的问题解决了， 现在我还有一个需求就是，上面的标题数字是需要动态改变的，这能做到吗？



> 您好，之前的问题解决了， 现在我还有一个需求就是，上面的标题数字是需要动态改变的，这能做到吗？

重新设置一下title的数组 updateUI一下

**Comment by liuyidao** [comment]
因为我用到wCustomMenuTitleSet设置了title的属性，updateTitle后所有设置的富文本属性 全部重置了，在重新调用wCustomMenuTitleSet方法也无效  请问有什么办法重新设置吗？

**Comment by wwmz** [comment]
> 因为我用到wCustomMenuTitleSet设置了title的属性，updateTitle后所有设置的富文本属性 全部重置了，在重新调用wCustomMenuTitleSet方法也无效 请问有什么办法重新设置吗？

查看Demo里的 WMZDemoTwo这个类 有你想要的
