### ISSUE TITLE
请问如何在右侧add自定义的view

### ISSUE THREAD

**Issue by YoungXKing** [wwmz/WMZPageController#15]
类似这种右侧有一个自定的view的需求。

直接在wCustomMenuViewSet(^(UIView *bgView){}回调里这样写：

XKCustomView * view =  [XKCustomView new];
[bgView addSubView:view];

这样恐怕不行吧，会重复add

**Comment by YoungXKing** [comment]
<img width="458" alt="截屏2020-09-03 下午6 37 22" src="https://user-images.githubusercontent.com/30762999/92105157-0000d580-ee15-11ea-9d2c-a7c067242150.png">
这种的需求

**Comment by YoungXKing** [comment]
pod无法导入该框架

**Comment by wwmz** [comment]
> <img alt="截屏2020-09-03 下午6 37 22" width="458" src="https://user-images.githubusercontent.com/30762999/92105157-0000d580-ee15-11ea-9d2c-a7c067242150.png">
> 
> 这种的需求

你直接接入两个标题就行了  把XKCustomView放在右边就行
设置.wMenuWidthSet(屏幕宽度/2)
然后在self.param = param;后面加入你的XKCustomView 注意延迟一下就行
 dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
          XKCustomView.frame = CGRectMake(屏幕宽度/2,0屏幕宽度/2,50);
         [self.upSc addSubview:XKCustomView];
  });

**Comment by YoungXKing** [comment]
> > <img alt="截屏2020-09-03 下午6 37 22" width="458" src="https://user-images.githubusercontent.com/30762999/92105157-0000d580-ee15-11ea-9d2c-a7c067242150.png">
> > 这种的需求
> 
> 你直接接入两个标题就行了 把XKCustomView放在右边就行
> 设置.wMenuWidthSet(屏幕宽度/2)
> 然后在self.param = param;后面加入你的XKCustomView 注意延迟一下就行
> dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
> XKCustomView.frame = CGRectMake(屏幕宽度/2,0屏幕宽度/2,50);
> [self.upSc addSubview:XKCustomView];
> });

好的！！感谢！
