### ISSUE TITLE
swift中，选中的title，再次点击，指示器的高度变了

### ISSUE THREAD

**Issue by Eonlychen** [wwmz/WMZPageController#16]
swift中，选中的title，再次点击，指示器的高度变了； 滑动没有问题。

**Comment by wwmz** [comment]
> swift中，选中的title，再次点击，指示器的高度变了； 滑动没有问题。

demo里的吗 我这没看出来。。

**Comment by Eonlychen** [comment]
不是demo里的， 我用pod依赖导入swift项目中产生的

**Comment by Eonlychen** [comment]
里面设置了一个headview，不会是这个导致的吧？

**Comment by wwmz** [comment]
> 里面设置了一个headview，不会是这个导致的吧？

可以加下群发下代码我看看呢

**Comment by Eonlychen** [comment]
可以的
