### ISSUE TITLE
请问如何动态修改标题数组

### ISSUE THREAD

**Issue by hujindong007** [wwmz/WMZPageController#17]

**Comment by wwmz** [comment]
> _No description provided._

               self.param
               .wTitleArrSet([self weiboData])
               .wViewControllerSet(^UIViewController *(NSInteger index) {
                   TestVC *vc = [TestVC new];
                    return vc;
               });
               //更新
               [self updateMenuData];

**Comment by hujindong007** [comment]
大佬 试了一下，动态改标题是可以了，但是因为重新绘制，每次都点击修改标题都会从头滚动到指定的位置，有什么方法可以固定不滚动

**Comment by wwmz** [comment]
> 大佬 试了一下，动态改标题是可以了，但是因为重新绘制，每次都点击修改标题都会从头滚动到指定的位置，有什么方法可以固定不滚动
wMenuDefaultIndex设置一下？默认滚动的index。。

**Comment by wwmz** [comment]
> 大佬 试了一下，动态改标题是可以了，但是因为重新绘制，每次都点击修改标题都会从头滚动到指定的位置，有什么方法可以固定不滚动

wMenuDefaultIndex设置一下？默认滚动的index。。

**Comment by hujindong007** [comment]
![B49A70794E76A53590D4FC9416D90CF6](https://user-images.githubusercontent.com/16041886/92360818-05656500-f120-11ea-9683-0243f5c05128.jpg)对的 记住上次选择的

**Comment by hujindong007** [comment]
我加了群里说吧
