### ISSUE TITLE
刷新的时候可以左右滚动

### ISSUE THREAD

**Issue by songguolin** [wwmz/WMZPageController#19]
你的demo刷新的时候不会左右滚动，但是相同代码写入我自己的工程，刷新的时候可以左右滚动，请问有什么特别的设置吗？

**Comment by wwmz** [comment]
> 你的demo刷新的时候不会左右滚动，但是相同代码写入我自己的工程，刷新的时候可以左右滚动，请问有什么特别的设置吗？

没有特别的设置哦 你说的头部的刷新 还是中间的刷新的时候

**Comment by songguolin** [comment]
中间刷新，这就很奇怪，我也尝试直接把你的代码导入工程，还是有这个问题，但是你的代码真机调试是没问题的

**Comment by wwmz** [comment]
> 中间刷新，这就很奇怪，我也尝试直接把你的代码导入工程，还是有这个问题，但是你的代码真机调试是没问题的

你的tableview的自动偏移有关掉吗 automaticallyAdjustsScrollViewInsets = NO

**Comment by songguolin** [comment]
关掉了的

**Comment by songguolin** [comment]
https://github.com/onurersel/UIView-GestureCallback 和这个手势封装有冲突，导致刷新的时候可以左右滚动

**Comment by wwmz** [comment]
> https://github.com/onurersel/UIView-GestureCallback 和这个手势封装有冲突，导致刷新的时候可以左右滚动

~ ~ 那你禁掉嘛 你加了这个手势我怎么可能监听的到，，，
