### ISSUE TITLE
DropMenu和pageController运行起来直接crash

### ISSUE THREAD

**Issue by mxpasser** [wwmz/WMZPageController#2]
DropMenu和pageController的代码运行起来后就挂了，报的如下exception！
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'section header height must not be negative - provided height for section 3 is -0.010000'

**Comment by wwmz** [comment]
这意思是headview标题高度变成了 -0.01 不能是负数 你是怎么结合的和 直接cocopod导入就会了吗

**Comment by wwmz** [comment]
你加我qq 925457662 给我看一下
