### ISSUE TITLE
设置wMenuTitleSelectUIFontSet无效

### ISSUE THREAD

**Issue by MoDaBao** [wwmz/WMZPageController#20]
想给选中状态和未选中状态设置不同的字体，同时设置了wMenuTitleUIFontSet和wMenuTitleSelectUIFontSet，生效的只有wMenuTitleUIFontSet

**Comment by wwmz** [comment]
> wMenuTitleSelectUIFontSet

.wMenuAnimalTitleBig设为YES

**Comment by wwmz** [comment]
> 想给选中状态和未选中状态设置不同的字体，同时设置了wMenuTitleUIFontSet和wMenuTitleSelectUIFontSet，生效的只有wMenuTitleUIFontSet

.wMenuAnimalTitleBig设为YES

**Comment by MoDaBao** [comment]
这个也设置了，也是无效的

**Comment by wwmz** [comment]
> 这个也设置了，也是无效的

你用哪个动画

**Comment by wwmz** [comment]
PageTitleMenuCircle， PageTitleMenuPDD，wMenuAnimalTitleBig这个属性默认是被我设为NO的

**Comment by MoDaBao** [comment]
> PageTitleMenuCircle， PageTitleMenuPDD，wMenuAnimalTitleBig这个属性默认是被我设为NO的

是这样啊，我用了PageTitleMenuPDD，改了动画生效了

**Comment by wwmz** [comment]
> > PageTitleMenuCircle， PageTitleMenuPDD，wMenuAnimalTitleBig这个属性默认是被我设为NO的
> 
> 是这样啊，我用了PageTitleMenuPDD，改了动画生效了

嗯嗯是的
