### ISSUE TITLE
使用了menu在导航栏的样式，子控制器里也需要嵌套一层menu，手指向上滑动时子控制器的menu在抖动

### ISSUE THREAD

**Issue by MoDaBao** [wwmz/WMZPageController#21]

**Comment by wwmz** [comment]
> _No description provided._
能截个图或者视频 看看吗

**Comment by MoDaBao** [comment]
[RPReplay_Final1602747266.MP4.zip](https://github.com/wwmz/WMZPageController/files/5383143/RPReplay_Final1602747266.MP4.zip)
视频不能传，只能打成压缩包了

**Comment by wwmz** [comment]
> [RPReplay_Final1602747266.MP4.zip](https://github.com/wwmz/WMZPageController/files/5383143/RPReplay_Final1602747266.MP4.zip)
> 视频不能传，只能打成压缩包了

我这两天正在优化嵌套这部分 改好你再通知你更新哈

**Comment by MoDaBao** [comment]
> > [RPReplay_Final1602747266.MP4.zip](https://github.com/wwmz/WMZPageController/files/5383143/RPReplay_Final1602747266.MP4.zip)
> > 视频不能传，只能打成压缩包了
> 
> 我这两天正在优化嵌套这部分 改好你再通知你更新哈
感谢感谢
对了，抖动的bug是开启悬浮才有，我还遇到一个bug，tableView列表展示不全，不知道是不是我代码哪里设置的问题
[RPReplay_Final1602831490.MP4.zip](https://github.com/wwmz/WMZPageController/files/5389794/RPReplay_Final1602831490.MP4.zip)

**Comment by wwmz** [comment]
> > > [RPReplay_Final1602747266.MP4.zip](https://github.com/wwmz/WMZPageController/files/5383143/RPReplay_Final1602747266.MP4.zip)
> > > 视频不能传，只能打成压缩包了
> > 
> > 
> > 我这两天正在优化嵌套这部分 改好你再通知你更新哈
> > 感谢感谢
> > 对了，抖动的bug是开启悬浮才有，我还遇到一个bug，tableView列表展示不全，不知道是不是我代码哪里设置的问题
> > [RPReplay_Final1602831490.MP4.zip](https://github.com/wwmz/WMZPageController/files/5389794/RPReplay_Final1602831490.MP4.zip)

+q群有问题直接提方便点
