### ISSUE TITLE
三级联动的时候互动出现问题了

### ISSUE THREAD

**Issue by zhufeng19940210** [wwmz/WMZPageController#24]
三级联动的时候互动出现问题了，手势冲突了

**Comment by wwmz** [comment]
> 三级联动的时候互动出现问题了，手势冲突了

我这主要是给个例子 实际的话 不同的嵌套场景 还是要用针对性的处理的

**Comment by wwmz** [comment]
> 三级联动的时候互动出现问题了，手势冲突了

我这主要是给个例子 实际的话 不同的嵌套场景 还是要用针对性的处理的 我这demo是没有针对特殊的 没那么智能适配各种场景的嵌套,最好还是要有一层把滑动关了

**Comment by zhufeng19940210** [comment]
好的收到了已经解决了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WMZ <notifications@github.com&gt;
发送时间: 2020年12月11日 15:16
收件人: wwmz/WMZPageController <WMZPageController@noreply.github.com&gt;
抄送: zhufneg <358244144@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[wwmz/WMZPageController] 三级联动的时候互动出现问题了 (#24)





  
三级联动的时候互动出现问题了，手势冲突了
  
我这主要是给个例子 实际的话 不同的嵌套场景 还是要用针对性的处理的 我这demo是没有针对特殊的 没那么智能适配各种场景的嵌套,最好还是要有一层把滑动关了

**Comment by wwmz** [comment]
> 好的收到了已经解决了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: WMZ <notifications@github.com&gt; 发送时间: 2020年12月11日 15:16 收件人: wwmz/WMZPageController <WMZPageController@noreply.github.com&gt; 抄送: zhufneg <358244144@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[wwmz/WMZPageController] 三级联动的时候互动出现问题了 (#24) 三级联动的时候互动出现问题了，手势冲突了 我这主要是给个例子 实际的话 不同的嵌套场景 还是要用针对性的处理的 我这demo是没有针对特殊的 没那么智能适配各种场景的嵌套,最好还是要有一层把滑动关了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哈 你可以把解决方法贴这里 让刚好遇到的人看到
