### ISSUE TITLE
可以监听标题的点击事件吗？切换不同标题，导航栏的title也要跟着变

### ISSUE THREAD

**Issue by xushengwei4656** [wwmz/WMZPageController#27]

**Comment by wwmz** [comment]
> _No description provided._
       //标题点击
       .wEventClickSet(^(id anyID, NSInteger index) {
           NSLog(@"标题点击%ld",index);
       })
       //控制器开始切换
       .wEventBeganTransferControllerSet(^(UIViewController *oldVC, UIViewController *newVC, NSInteger oldIndex, NSInteger newIndex) {
           NSLog(@"开始切换 %ld %ld",oldIndex,newIndex);
        })
       //控制器结束切换
       .wEventEndTransferControllerSet(^(UIViewController *oldVC, UIViewController *newVC, NSInteger oldIndex, NSInteger newIndex) {
          NSLog(@"结束切换 %ld %ld",oldIndex,newIndex);
        })

**Comment by xushengwei4656** [comment]
谢谢大佬
