### ISSUE TITLE
请问互相嵌套使用时，如何禁止 子 WMZPageController 左右滑动

### ISSUE THREAD

**Issue by 90candy** [wwmz/WMZPageController#28]
两个 WMZPageController 互相嵌套使用，目前不做处理时为 子WMZPageController可以滚动，父WMZPageController滚动不了，可否任意控制

**Comment by wwmz** [comment]
> 两个 WMZPageController 互相嵌套使用，目前不做处理时为 子WMZPageController可以滚动，父WMZPageController滚动不了，可否任意控制

不会吧 你怎么嵌套的 你说的任意控制指的是啥
