### ISSUE TITLE
您好，菜单栏未吸顶时，子控制器左右滑动时，能否禁止上下滑动

### ISSUE THREAD

**Issue by dylwwj123** [wwmz/WMZPageController#29]
我的顶部自定义视图挺长的，我发现了当菜单栏吸顶的时候，左右滑动是不可以上下滑动的， 但是当菜单栏还未吸顶时，子控制器可以边左右滑边上下滑。。

**Comment by wwmz** [comment]
可以吧 你看我demo 这个上次加过了 pod.1.3.3可能有更新------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wenshuai&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月22日(星期五) 晚上8:05
收件人:&nbsp;&quot;wwmz/WMZPageController&quot;<WMZPageController@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wwmz/WMZPageController] 您好，菜单栏未吸顶时，子控制器左右滑动时，能否禁止上下滑动 (#29)

**Comment by wwmz** [comment]
> 可以吧 你看我demo 这个上次加过了 pod.1.3.3可能有更新



> 我的顶部自定义视图挺长的，我发现了当菜单栏吸顶的时候，左右滑动是不可以上下滑动的， 但是当菜单栏还未吸顶时，子控制器可以边左右滑边上下滑。。

可以吧 你看我demo 这个上次加过了 pod.1.3.3可能有更新
