### ISSUE TITLE
PageController基类是uitableview, 要是uicollecitonview的子视图是不是没法用？

### ISSUE THREAD

**Issue by Jshto** [wwmz/WMZPageController#32]
PageController基类是uitableview, 要是uicollecitonview的子视图是不是没法用？

**Comment by wwmz** [comment]
> PageController基类是uitableview, 要是uicollecitonview的子视图是不是没法用？

可以啊。。不是还有另一个协议 传UIScrollView的吗。。 是一样的 只要能滚动的就可以 demo不是有collectionview的例子么
