### ISSUE TITLE
多个两层嵌套的时候，滑动会出现问题

### ISSUE THREAD

**Issue by JunCheng312** [wwmz/WMZPageController#35]
麻烦看下

**Comment by wwmz** [comment]
> 麻烦看下

暂时没时间优化 哈 先自己关掉一个滑动吧 wScrollCanTransfer

**Comment by wwmz** [comment]
> 麻烦看下

过年放假了懂的都懂 年后再优化了

**Comment by wwmz** [comment]
> 麻烦看下

1.4.0 已修复多层嵌套的问题

**Comment by wwmz** [comment]
> 麻烦看下

1.4.0 已修复嵌套的手势问题
