### ISSUE TITLE
交流群突然解散了大佬是不是出了什么问题

### ISSUE THREAD

**Issue by jianjianhao** [wwmz/WMZPageController#36]

**Comment by wwmz** [comment]
没有哈哈 无力回复那么多 提issuse吧------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;jianjianhao&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月3日(星期三) 晚上8:14
收件人:&nbsp;&quot;wwmz/WMZPageController&quot;<WMZPageController@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wwmz/WMZPageController] 交流群突然解散了大佬是不是出了什么问题 (#36)
