### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by taozl** [wwmz/WMZPageController#37]
首先感谢作者提供的优秀的三方，希望能继续更新下去。这里我遇到这个问题：

我将param设置成
.wMenuAnimalSet(PageTitleMenuAiQY)///爱奇艺样式(依恋)

然后动态的添加[self addMenuTitleWithObject:[WMZPageTitleDataModel initWithIndex:0 controller:AddVC title:@"增加的标题"]]

发现指示器的位置滑动到了第0个，并没有在当前的索引中。

**Comment by wwmz** [comment]
> 首先感谢作者提供的优秀的三方，希望能继续更新下去。这里我遇到这个问题：
> 
> 我将param设置成
> .wMenuAnimalSet(PageTitleMenuAiQY)///爱奇艺样式(依恋)
> 
> 然后动态的添加[self addMenuTitleWithObject:[WMZPageTitleDataModel initWithIndex:0 controller:AddVC title:@"增加的标题"]]
> 
> 发现指示器的位置滑动到了第0个，并没有在当前的索引中。

这个动态方法忘处理 下划线了哈。。抽时间我加上

**Comment by taozl** [comment]
我是在  添加的方法里面加了 
[self.upSc.mainView scrollToIndex:self.upSc.currentTitleIndex animal:NO];
这句代码，目前是解决了这个问题，但不知道是否有其他更好的方案

**Comment by wwmz** [comment]
> 我是在 添加的方法里面加了
> [self.upSc.mainView scrollToIndex:self.upSc.currentTitleIndex animal:NO];
> 这句代码，目前是解决了这个问题，但不知道是否有其他更好的方案

没问题的 这行代码
