### ISSUE TITLE
大佬,我曾经提到的问题并没有很好的解决，我特意写了个demo辛苦抽空看下。

### ISSUE THREAD

**Issue by iDidDo** [wwmz/WMZPageController#38]
主要问题是
1、吸顶后颜色改变了，但是左右滑动颜色又变回了原有色。
2、当collectionview的cell不足一屏，触摸cllectionview区域，上下滑动失灵，就是无法上下滑动。

Demo已写好，现象也是可以重现的，辛苦抽空看下。
GitHub链接：
https://github.com/iDidDo/WMZDemo.git

**Comment by wwmz** [comment]
好的 等复工了看看------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;iDidDo&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月19日(星期五) 上午10:55
收件人:&nbsp;&quot;wwmz/WMZPageController&quot;<WMZPageController@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wwmz/WMZPageController] 大佬,我曾经提到的问题并没有很好的解决，我特意写了个demo辛苦抽空看下。 (#38)

**Comment by iDidDo** [comment]
大佬还没上班吗

**Comment by wwmz** [comment]
> 大佬还没上班吗

我下载了你的demo 我啥也没改先pod更新至1.3.5 然后没问题哦 不足一屏可以滑动啊   你第一个问题 左右滑动那个会  是因为我在切换标题的时候重设了 背景色  你需要做的处理是在自定义wCustomMenuSelectTitle 里再根据偏移量 设置一下背景色

**Comment by iDidDo** [comment]
你用的模拟器系统多少？

**Comment by wwmz** [comment]
> 你用的模拟器系统多少？

最新的14
