### ISSUE TITLE
选中菜单中某index的视图时，手机锁屏在解锁，当前选中的视图会叠加

### ISSUE THREAD

**Issue by ghostMD** [wwmz/WMZPageController#39]
<img width="439" alt="截屏2021-03-23 16 07 51" src="https://user-images.githubusercontent.com/19319644/112113583-f5abfa80-8bf1-11eb-86a7-4dea5ebc48d7.png">

**Comment by wwmz** [comment]
你这不是最新代码吧 建议先更新最新代码哦
