### ISSUE TITLE
美团模式时底部固定视图问题

### ISSUE THREAD

**Issue by janshky-zuo** [wwmz/WMZPageController#40]
底部固定视图要实现getMyTableView或者getMyScrollView，但如果用美团模式左右两个table联动时底部固定有什么好的办法吗

**Comment by wwmz** [comment]
> 底部固定视图要实现getMyTableView或者getMyScrollView，但如果用美团模式左右两个table联动时底部固定有什么好的办法吗

里面不是有例子吗。你仔细看？？美团demo 底部多个tableview

**Comment by wwmz** [comment]
> 底部固定视图要实现getMyTableView或者getMyScrollView，但如果用美团模式左右两个table联动时底部固定有什么好的办法吗

getMyScrollViews 有例子呀

**Comment by janshky-zuo** [comment]
> > 底部固定视图要实现getMyTableView或者getMyScrollView，但如果用美团模式左右两个table联动时底部固定有什么好的办法吗
> 
> getMyScrollViews 有例子呀

![image](https://user-images.githubusercontent.com/30853582/112601572-93e7cc80-8e4d-11eb-91e5-f5d119278d0d.png)
我看了内部的实现，返回getMyScrollViews后  UIScrollView *view = nil 这个view没有赋值，会导致后面的
[self.sonChildFooterViewDic setObject:view forKey:@(index)];报错
我在这里手动将 view = self.currentScrollArr.lastObject 处理了下

**Comment by wwmz** [comment]
> > > 底部固定视图要实现getMyTableView或者getMyScrollView，但如果用美团模式左右两个table联动时底部固定有什么好的办法吗
> > 
> > 
> > getMyScrollViews 有例子呀
> 
> ![image](https://user-images.githubusercontent.com/30853582/112601572-93e7cc80-8e4d-11eb-91e5-f5d119278d0d.png)
> 我看了内部的实现，返回getMyScrollViews后 UIScrollView *view = nil 这个view没有赋值，会导致后面的
> [self.sonChildFooterViewDic setObject:view forKey:@(index)];报错
> 我在这里手动将 view = self.currentScrollArr.lastObject 处理了下

那可能是设置错值了吧 应该是要设置tmpView才对

**Comment by janshky-zuo** [comment]
![image](https://user-images.githubusercontent.com/30853582/112784266-c67b0a80-9083-11eb-9bfb-8f3af9e2df85.png)
作者ni你好，源码中底部视图是根据scrollView的offsetX在动态改变width,这样在滚动的时候会挤压bottomView的内容，可否改为动态赋值坐标x

**Comment by wwmz** [comment]
> ![image](https://user-images.githubusercontent.com/30853582/112784266-c67b0a80-9083-11eb-9bfb-8f3af9e2df85.png)
> 作者ni你好，源码中底部视图是根据scrollView的offsetX在动态改变width,这样在滚动的时候会挤压bottomView的内容，可否改为动态赋值坐标x

1.3.7已更新为x改变的方式
