### ISSUE TITLE
crash  when  “newVC == nil”

### ISSUE THREAD

**Issue by Mr-yuwei** [wwmz/WMZPageController#41]
```
这个方法取值为空未做兼容，导致闪退
- (UIViewController*)getVCWithIndex:(NSInteger)index{
    if (index < 0|| index >= self.param.wControllers.count) {
        return nil;
    }
    if ([[self findBelongViewControllerForView:self].cache objectForKey:@(index)]) {
        return [[self findBelongViewControllerForView:self].cache objectForKey:@(index)];
    }
    return self.param.wControllers[index];
}
```

```
   UIViewController *newVC = [self getVCWithIndex:index];
   [newVC beginAppearanceTransition:YES animated:YES];
   [self addChildVC:index VC:newVC];
```
```
- (void)addChildVC:(NSInteger)index VC:(UIViewController*)newVC{
    if (![[self findBelongViewControllerForView:self].childViewControllers containsObject:newVC]) {
        [[self findBelongViewControllerForView:self] addChildViewController:newVC];
        CGRect frame = CGRectMake(index * self.dataView.frame.size.width,0,self.dataView.frame.size.width,
                                  self.dataView.frame.size.height);
        newVC.view.frame = frame;
        [self.dataView addSubview:newVC.view];
        [newVC didMoveToParentViewController:[self findBelongViewControllerForView:self]];
        [[self findBelongViewControllerForView:self].cache setObject:newVC forKey:@(index)];
    }
}
```

**Comment by wwmz** [comment]
> ```
> 这个方法取值为空未做兼容，导致闪退
> - (UIViewController*)getVCWithIndex:(NSInteger)index{
>     if (index < 0|| index >= self.param.wControllers.count) {
>         return nil;
>     }
>     if ([[self findBelongViewControllerForView:self].cache objectForKey:@(index)]) {
>         return [[self findBelongViewControllerForView:self].cache objectForKey:@(index)];
>     }
>     return self.param.wControllers[index];
> }
> ```
> 
> ```
>    UIViewController *newVC = [self getVCWithIndex:index];
>    [newVC beginAppearanceTransition:YES animated:YES];
>    [self addChildVC:index VC:newVC];
> ```
> 
> ```
> - (void)addChildVC:(NSInteger)index VC:(UIViewController*)newVC{
>     if (![[self findBelongViewControllerForView:self].childViewControllers containsObject:newVC]) {
>         [[self findBelongViewControllerForView:self] addChildViewController:newVC];
>         CGRect frame = CGRectMake(index * self.dataView.frame.size.width,0,self.dataView.frame.size.width,
>                                   self.dataView.frame.size.height);
>         newVC.view.frame = frame;
>         [self.dataView addSubview:newVC.view];
>         [newVC didMoveToParentViewController:[self findBelongViewControllerForView:self]];
>         [[self findBelongViewControllerForView:self].cache setObject:newVC forKey:@(index)];
>     }
> }
> ```

为什么会赋个空的vc呢

**Comment by wwmz** [comment]
> ```
> 这个方法取值为空未做兼容，导致闪退
> - (UIViewController*)getVCWithIndex:(NSInteger)index{
>     if (index < 0|| index >= self.param.wControllers.count) {
>         return nil;
>     }
>     if ([[self findBelongViewControllerForView:self].cache objectForKey:@(index)]) {
>         return [[self findBelongViewControllerForView:self].cache objectForKey:@(index)];
>     }
>     return self.param.wControllers[index];
> }
> ```
> 
> ```
>    UIViewController *newVC = [self getVCWithIndex:index];
>    [newVC beginAppearanceTransition:YES animated:YES];
>    [self addChildVC:index VC:newVC];
> ```
> 
> ```
> - (void)addChildVC:(NSInteger)index VC:(UIViewController*)newVC{
>     if (![[self findBelongViewControllerForView:self].childViewControllers containsObject:newVC]) {
>         [[self findBelongViewControllerForView:self] addChildViewController:newVC];
>         CGRect frame = CGRectMake(index * self.dataView.frame.size.width,0,self.dataView.frame.size.width,
>                                   self.dataView.frame.size.height);
>         newVC.view.frame = frame;
>         [self.dataView addSubview:newVC.view];
>         [newVC didMoveToParentViewController:[self findBelongViewControllerForView:self]];
>         [[self findBelongViewControllerForView:self].cache setObject:newVC forKey:@(index)];
>     }
> }
> ```

就算是nil也不会闪退啊 我试了一下没重现闪退的情况

**Comment by wwmz** [comment]
> ```
> 这个方法取值为空未做兼容，导致闪退
> - (UIViewController*)getVCWithIndex:(NSInteger)index{
>     if (index < 0|| index >= self.param.wControllers.count) {
>         return nil;
>     }
>     if ([[self findBelongViewControllerForView:self].cache objectForKey:@(index)]) {
>         return [[self findBelongViewControllerForView:self].cache objectForKey:@(index)];
>     }
>     return self.param.wControllers[index];
> }
> ```
> 
> ```
>    UIViewController *newVC = [self getVCWithIndex:index];
>    [newVC beginAppearanceTransition:YES animated:YES];
>    [self addChildVC:index VC:newVC];
> ```
> 
> ```
> - (void)addChildVC:(NSInteger)index VC:(UIViewController*)newVC{
>     if (![[self findBelongViewControllerForView:self].childViewControllers containsObject:newVC]) {
>         [[self findBelongViewControllerForView:self] addChildViewController:newVC];
>         CGRect frame = CGRectMake(index * self.dataView.frame.size.width,0,self.dataView.frame.size.width,
>                                   self.dataView.frame.size.height);
>         newVC.view.frame = frame;
>         [self.dataView addSubview:newVC.view];
>         [newVC didMoveToParentViewController:[self findBelongViewControllerForView:self]];
>         [[self findBelongViewControllerForView:self].cache setObject:newVC forKey:@(index)];
>     }
> }
> ```

哦 我知道了 你代码不是最新的 我目前的代码
- (void)addChildVC:(NSInteger)index VC:(UIViewController*)newVC{
    if (!newVC) return;
} 是有置空处理的 建议先更新一下最新代码哦
