### ISSUE TITLE
搭配CYLTabBarController使用时，布局会出现问题，是否不兼容?

### ISSUE THREAD

**Issue by blmyself** [wwmz/WMZPageController#43]
用的是demo里微博嵌套的方式，然后项目里用到了CYLTabBarController，发现一起使用进有问题，如视频:

https://user-images.githubusercontent.com/914295/119106500-01c90280-ba51-11eb-8fda-f6ac7c6d50df.mov

测试环境是: Xcode 12.3 +   iPhone 12 pro max 14.3模拟器

**Comment by wwmz** [comment]
> 用的是demo里微博嵌套的方式，然后项目里用到了CYLTabBarController，发现一起使用进有问题，如视频:
> 
>  2021-05-21.4.20.06.mov 
> 测试环境是: Xcode 12.3 + iPhone 12 pro max 14.3模拟器

调整一下底部的距离就行了 //自定义整体距离顶部的位置(如果默认算的不准确 或者需要修改) block内会传回当前的值 可对比自行返回最终需要的
WMZPagePropStatementAndPropSetFuncStatement(copy, WMZPageParam, PageCustomFrameY,        wCustomNaviBarY)
//自定义整体距离底部的位置(如果默认算的不准确 或者需要修改) block内会传回当前的值 可对比自行返回最终需要的
WMZPagePropStatementAndPropSetFuncStatement(copy, WMZPageParam, PageCustomFrameY,        wCustomTabbarY)

**Comment by blmyself** [comment]
知通原因了，嵌套使用的主vc不能用xib，我把xib删掉了布局就好了
