### ISSUE TITLE
有个小bug，希望改进一下

### ISSUE THREAD

**Issue by dylwwj123** [wwmz/WMZPageController#44]
最新的demo里改的 ，两级嵌套的时候，子级自定义头部滑不动

<img width="375" alt="WeChat18fa0401ace7551c1a03ce7ef2598252" src="https://user-images.githubusercontent.com/18459782/119340110-a30bbf00-bcc4-11eb-822a-17a5602570b8.png">

**Comment by wwmz** [comment]
> 最新的demo里改的 ，两级嵌套的时候，子级自定义头部滑不动
> 
> <img alt="WeChat18fa0401ace7551c1a03ce7ef2598252" width="375" src="https://user-images.githubusercontent.com/18459782/119340110-a30bbf00-bcc4-11eb-822a-17a5602570b8.png">

嵌套里手势冲突了 加了一段代码解决了头部滑动问题 但是没完美解决 会左右滑动的时候还能往上拖动 要完美解决只能把左右滑动关了
