### ISSUE TITLE
添加自定义view无法带到最顶层

### ISSUE THREAD

**Issue by GSmoke** [wwmz/WMZPageController#45]
1.WMZPageController的子控制器作为UITableBarController的子控制器
2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view];
3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view
4.版本号1.3.7

**Comment by wwmz** [comment]
> 1.WMZPageController的子控制器作为UITableBarController的子控制器
> 2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view];
> 3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view
> 4.版本号1.3.7

?有图吗 你这是让我自己去按步骤复现吗。。。~ ~

**Comment by wwmz** [comment]
> 1.WMZPageController的子控制器作为UITableBarController的子控制器
> 2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view];
> 3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view
> 4.版本号1.3.7

延迟个0.2秒添加这个自定义view

**Comment by GSmoke** [comment]
好的 我试一下



在 2021-05-26 13:44:32，"WMZ" ***@***.***> 写道：

1.WMZPageController的子控制器作为UITableBarController的子控制器
2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view];
3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view
4.版本号1.3.7

延迟个0.2秒添加这个自定义view

**Comment by GSmoke** [comment]
延迟0.2秒可以了,能告知原因吗,谢谢


















在 2021-05-26 13:44:32，"WMZ" ***@***.***> 写道：

1.WMZPageController的子控制器作为UITableBarController的子控制器
2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view];
3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view
4.版本号1.3.7

延迟个0.2秒添加这个自定义view

**Comment by wwmz** [comment]
> 延迟0.2秒可以了,能告知原因吗,谢谢 在 2021-05-26 13:44:32，"WMZ" ***@***.***> 写道： 1.WMZPageController的子控制器作为UITableBarController的子控制器 2.WMZPageController的view添加一个自定义view,并[self.view bringSubviewToFront:self.自定义view]; 3.window的根控制器由其他控制器切换为上面的UITableBarController控制器的时候并不能展示出上面的自定义view 4.版本号1.3.7 延迟个0.2秒添加这个自定义view — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

pageController加载的时候延迟了0.1秒去布局要自动计算一些布局等 你不延迟的话就会被覆盖在最底部
