### ISSUE TITLE
指示器与menView底部的间隙如何调整?谢谢

### ISSUE THREAD

**Issue by GSmoke** [wwmz/WMZPageController#46]
指示器与menView的间隙如何调整?谢谢
![image](https://user-images.githubusercontent.com/33562859/119609612-72de3080-be2a-11eb-96a2-23a8847b1d74.png)

**Comment by wwmz** [comment]
> 指示器与menView的间隙如何调整?谢谢
> ![image](https://user-images.githubusercontent.com/33562859/119609612-72de3080-be2a-11eb-96a2-23a8847b1d74.png)

wMenuIndicatorY 传入正负值

**Comment by GSmoke** [comment]
传入正值2
