### ISSUE TITLE
代码规范的问题

### ISSUE THREAD

**Issue by Mr-yuwei** [wwmz/WMZPageController#47]
######    WMZPageController 
  
  1. 生命周期方法，是否需要拆分.如：`viewWillAppear`逻辑编写是否过多。
  2. if-else方法是否存在太多。如：“UI”【大方法拆分】

######  WMZPagePropStatementAndPropSetFuncStatement是否可取，个人觉得会影响代码可读性。

**Comment by wwmz** [comment]
> WMZPagePropStatementAndPropSetFuncStatement
抽空会去优化一下
不过WMZPagePropStatementAndPropSetFuncStatement 怎么会影响可读性呢。。就当成普通属性就行了

**Comment by wwmz** [comment]
> ###### WMZPageConfig文件宏定义前缀问题,枚举值的定义，目前都缺少。
> ###### WMZPageController
> 1. 生命周期方法，是否需要拆分.如：`viewWillAppear`逻辑编写是否过多。
> 2. if-else方法是否存在太多。如：“UI”【大方法拆分】
> 
> ###### WMZPagePropStatementAndPropSetFuncStatement是否可取，个人觉得会影响代码可读性。

抽空会去优化一下
不过WMZPagePropStatementAndPropSetFuncStatement 怎么会影响可读性呢。。就当成普通属性就行了
