### ISSUE TITLE
细节还需完善

### ISSUE THREAD

**Issue by lxm1799** [wwmz/WMZPageController#48]
1、title的左侧间距无法调整
2、title栏目view，无法调整左右边距，只能设置宽度
3、右侧固定的按钮无法自定义，建议是右侧暴露出一个view,让使用者自定义view，且可设置size

正好这几个都是项目中需要的....

**Comment by wwmz** [comment]
> 1、title的左侧间距无法调整
> 2、title栏目view，无法调整左右边距，只能设置宽度
> 3、右侧固定的按钮无法自定义，建议是右侧暴露出一个view,让使用者自定义view，且可设置size
> 
> 正好这几个都是项目中需要的....

1 wMenuTitleOffset 调整标题间的间距 2 可以延迟0.1秒设置    
    self.upSc.mainView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0) 内边距调整整体左右侧间距  3 wCustomMenufixTitle 自定义固定标题

**Comment by lxm1799** [comment]
wCustomMenufixTitleSet这个自定义的方法没有demo出现，尝试了下，一直使用不了...

**Comment by wwmz** [comment]
> wCustomMenufixTitleSet这个自定义的方法没有demo出现，尝试了下，一直使用不了...

    param.wCustomMenufixTitle = ^(NSArray<WMZPageNaviBtn *> * _Nullable titleArr) {
        
    }
