### ISSUE TITLE
怎样与swift混编？

### ISSUE THREAD

**Issue by LiFuPeng** [wwmz/WMZPageController#49]
好轮子
但是怎样与swift混编？
.wTitleArrSet(data)一直报 Argument passed to call that takes no arguments错误

**Comment by wwmz** [comment]
> 好轮子
> 但是怎样与swift混编？
> .wTitleArrSet(data)一直报 Argument passed to call that takes no arguments错误

demo里不是有swift使用示范么。         
           let param:WMZPageParam = PageParam()
            .wTitleArrSet()(["第一页","第二页"])
            .wViewControllerSet()({(index:NSInteger)->(UIViewController?)in
                return TestVC();
            })
            .wMenuPositionSet()(.init(3))
            .wMenuAnimalSet()(.init(5))
            .wMenuTitleWidthSet()(100)
            .wMenuWidthSet()(200)
            .wMenuIndicatorYSet()(5)
           self.param = param;

**Comment by LiFuPeng** [comment]
之前没看到，不好意思
