### ISSUE TITLE
自定义标题

### ISSUE THREAD

**Issue by MoDaBao** [wwmz/WMZPageController#50]
标题展示动图如何实现呢

**Comment by wwmz** [comment]
> 标题展示动图如何实现呢  

    //自定义静态标题
    .wCustomMenuTitleSet(^(NSArray *titleArr) {
        [titleArr enumerateObjectsUsingBlock:^(WMZPageNaviBtn*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            [obj sd_setImageWithURL:[NSURL URLWithString:@"https://upload-images.jianshu.io/upload_images/9163368-02e26751674a3bc6.jpeg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240"] forState:UIControlStateNormal];
        }];
    })
    //自定义滑动后标题的变化 (如有需要)
    .wCustomMenuSelectTitleSet(^(NSArray *titleArr) {
        [titleArr enumerateObjectsUsingBlock:^(WMZPageNaviBtn*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            [obj sd_setImageWithURL:[NSURL URLWithString:@"https://upload-images.jianshu.io/upload_images/9163368-02e26751674a3bc6.jpeg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240"] forState:UIControlStateNormal];
        }];
    });
如果还带了文字  可能会由图片尺寸导致图文偏移的问题 要自己调整一下 
//设置图文位置
- (void)TagSetImagePosition:(PageBtnPosition)postion spacing:(CGFloat)spacing; 用WMZPageNaviBtn的这个方法

**Comment by MoDaBao** [comment]
设置了图片并且设置了图片的EdgeInsets改变图片大小
但是文字显示不出来

**Comment by wwmz** [comment]
> 设置了图片并且设置了图片的EdgeInsets改变图片大小
> 但是文字显示不出来

obj再set一下title试试

**Comment by MoDaBao** [comment]
[titleArr enumerateObjectsUsingBlock:^(WMZPageNaviBtn*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
            [obj TagSetImagePosition:PageBtnPositionLeft spacing:1];
            [obj setBackgroundColor:UIColor.qmui_randomColor];
            obj.imageView.contentMode = UIViewContentModeScaleAspectFill;
            [obj setImageEdgeInsets:UIEdgeInsetsMake(10, 10, 10, 100)];
            [obj setTitleEdgeInsets:UIEdgeInsetsMake(10, 100, 10, 10)];
            [obj setImageWithImage:@"https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171021%2F74d2ff3fc7e24e40926cd52ec77a495e.gif&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627178597&t=061209c7b49d110e56c5ea7962c8225a" placeholderImage:nil];
            [obj setTitle:@"sksk" forState:UIControlStateNormal];
        }];

设置了没效果 代码是这样的

**Comment by wwmz** [comment]
> setImageWithImage

setImageWithImage这个方法可能有

> https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171021%2F74d2ff3fc7e24e40926cd52ec77a495e.gif&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627178597&t=061209c7b49d110e56c5ea7962c8225a

你要等网络图片加载出来了 才去调整图文的位置 以sdwebimage为例 
          [obj sd_setImageWithURL:[NSURL URLWithString:@"https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171021%2F74d2ff3fc7e24e40926cd52ec77a495e.gif&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627178597&t=061209c7b49d110e56c5ea7962c8225a"] forState:UIControlStateNormal completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
                        [obj TagSetImagePosition:PageBtnPositionTop spacing:0];
         } ];  试试 很接近了

**Comment by wwmz** [comment]
> [titleArr enumerateObjectsUsingBlock:^(WMZPageNaviBtn* _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
> [obj TagSetImagePosition:PageBtnPositionLeft spacing:1];
> [obj setBackgroundColor:UIColor.qmui_randomColor];
> obj.imageView.contentMode = UIViewContentModeScaleAspectFill;
> [obj setImageEdgeInsets:UIEdgeInsetsMake(10, 10, 10, 100)];
> [obj setTitleEdgeInsets:UIEdgeInsetsMake(10, 100, 10, 10)];
> [obj setImageWithImage:@"https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171021%2F74d2ff3fc7e24e40926cd52ec77a495e.gif&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627178597&t=061209c7b49d110e56c5ea7962c8225a" placeholderImage:nil];
> [obj setTitle:@"sksk" forState:UIControlStateNormal];
> }];
> 
> 设置了没效果 代码是这样的

你要等网络图片加载出来了 才去调整图文的位置 以sdwebimage为例
[obj sd_setImageWithURL:[NSURL URLWithString:@"https://gimg2.baidu.com/image_search/src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171021%2F74d2ff3fc7e24e40926cd52ec77a495e.gif&refer=http%3A%2F%2F5b0988e595225.cdn.sohucs.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1627178597&t=061209c7b49d110e56c5ea7962c8225a"] forState:UIControlStateNormal completed:^(UIImage * _Nullable image, NSError * _Nullable error, SDImageCacheType cacheType, NSURL * _Nullable imageURL) {
[obj TagSetImagePosition:PageBtnPositionTop spacing:0];
} ]; 试试 很接近了
