### ISSUE TITLE
selectMenuWithIndex不能立即生效？

### ISSUE THREAD

**Issue by wzw110110** [wwmz/WMZPageController#51]
您好大佬，麻烦问下，默认选中某个index页面，selectMenuWithIndex不能立即生效，我加了个延迟0.1秒才会选中这个页面，请问是什么原因呀？

**Comment by wwmz** [comment]
> 您好大佬，麻烦问下，默认选中某个index页面，selectMenuWithIndex不能立即生效，我加了个延迟0.1秒才会选中这个页面，请问是什么原因呀？

调用代码呢 一般可以立即生效的
