### ISSUE TITLE
必须要继承WMZPageController吗？业务已经继承了BaseController

### ISSUE THREAD

**Issue by lumangmang** [wwmz/WMZPageController#52]

**Comment by wwmz** [comment]
> _No description provided._
你可以拖动进去项目 让这个 WMZPageController 继承你的BaseController，      
我写代码一般作为BaseController的都是通过实现协议实现对应方法和配置的  所以我使用WMZPageController的时候也是实现Base的协议就可以就不用继承我的baseVC了

**Comment by lumangmang** [comment]
好的    还有一个  标题是从网络获取的  如何更新   我看demo好像没有

**Comment by wwmz** [comment]
> 好的 还有一个 标题是从网络获取的 如何更新 我看demo好像没有
self.param.wTitle = @[]   后调用实例方法即可
/// @brief 更新菜单栏
- (void)updateMenuData;

/// @brief 标题数量内容不变情况下只更新内容
- (void)updateTitle;

**Comment by lumangmang** [comment]
不行 还是没法用 因为我们的项目是mvvm 不能这样继承  而且第三方是用Pod管理，所以我觉得还是能不要强制继承 这样侵入性太强

**Comment by lumangmang** [comment]
我们的BaseController是swift写的 所以也导致无法让WMZPageController直接继承，问题太多...

**Comment by wwmz** [comment]
> 不行 还是没法用 因为我们的项目是mvvm 不能这样继承 而且第三方是用Pod管理，所以我觉得还是能不要强制继承 这样侵入性太强

你这base是swift 那就没啥好办法了 其实base里一般也没啥东西  就一些通用的
