### ISSUE TITLE
1.4.1为何还不能更新，我正需要解决FD的滑动返回问题

### ISSUE THREAD

**Issue by 542604974** [wwmz/WMZPageController#56]
[!] CocoaPods could not find compatible versions for pod "WMZPageController":
  In Podfile:
    WMZPageController (~> 1.4.1)

None of your spec sources contain a spec satisfying the dependency: `WMZPageController (~> 1.4.1)`.

**Comment by 542604974** [comment]
更新了还是不行，在等几天看吧

**Comment by wwmz** [comment]
> ![截屏2021-10-16 下午3 16 18](https://user-images.githubusercontent.com/15099430/137577893-8d62e6c7-f7ad-4c93-a955-5cafc643a149.png) 还有一个问题，为啥这个view穿出来

你是怎么设置的

**Comment by 542604974** [comment]
// 正常的话是会悬浮到状态栏那里，改变这里减掉一部分就会自动悬浮到自定义导航栏那里)
    .wCustomDataViewHeightSet(^CGFloat(CGFloat nowY) {
        return nowY + PageVCStatusBarHeight;
    })
    .wBouncesSet(YES)
    //No为从自定义导航栏顶部开始 yes为从自定义导航栏底部开始
    .wFromNaviSet(YES)

**Comment by wwmz** [comment]
> .wCustomDataViewHeightSet(^CGFloat(CGFloat nowY) {
>     return nowY + PageVCStatusBarHeight;
> })

.wCustomDataViewHeightSet(^CGFloat(CGFloat nowY) {
    return nowY + PageVCStatusBarHeight;
})这里视实际情况更改 有时候不需要更改 无需调用
