### ISSUE TITLE
下拉头视图缩放问题

### ISSUE THREAD

**Issue by ryanll** [wwmz/WMZPageController#57]
下拉头视图在返回的UIImageView添加view，图片缩放时，view的大小和位置也会进行缩放，可以不让子视图缩放吗

**Comment by wwmz** [comment]
> 下拉头视图在返回的UIImageView添加view，图片缩放时，view的大小和位置也会进行缩放，可以不让子视图缩放吗

你试试view不要添加在UIImageView上 添加在headView上 看我的代码试试
/// 其他视图加在 tableHeaderView上
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1* NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
UIView *headView = self.downSc.tableHeaderView;
///要加的view
UIView *view = UIView.new;
view.backgroundColor = UIColor.redColor;
view.frame = CGRectMake(0, 0, PageVCWidth, 100);
[headView addSubview:view];
});
