### ISSUE TITLE
导航栏渐变样式，push之后再pop回来后页面下沉，导航栏会直接变黑色

### ISSUE THREAD

**Issue by miaojia** [wwmz/WMZPageController#6]

**Comment by wwmz** [comment]
具体代码呢

**Comment by miaojia** [comment]
> 具体代码呢

这个问题我已经修复，但是遇到了另一个问题，子控制器的显示问题，底部大概有一个tab的留白
NSArray *data=@[@"活动行程",@"申请记录"];
    
    NSMutableArray *vcArr=[NSMutableArray new];
    [vcArr addObject:[[MJGoTableViewController alloc]init]];
    [vcArr addObject:[[MJGoApplyTableViewController alloc]init]];
    
    
    WMZPageParam *param = PageParam()
    .wTitleArrSet(data)
    .wMenuTitleOffsetSet(16.5*MJSCALE)
    .wMenuTitleSelectColorSet(UIColorWhite)
    .wMenuTitleColorSet(UIColorWithHexString(@"#FFFFFF"))
    .wMenuAnimalSet(3)
    .wMenuIndicatorWidthSet(28*MJSCALE)
    .wMenuCellMarginSet(16.5*MJSCALE)
    .wMenuBgColorSet(UIColorWithHexString(@"#4B4B4B"))
    .wMenuCellMarginYSet(20*MJSCALEH)
    .wFromNaviSet(NO)
    .wControllersSet(vcArr);
    self.param = param;

**Comment by miaojia** [comment]
> > 具体代码呢
> 
> 这个问题我已经修复，但是遇到了另一个问题，子控制器的显示问题，底部大概有一个tab的留白
> NSArray *data=@[@"活动行程",@"申请记录"];
> 
> ```
> NSMutableArray *vcArr=[NSMutableArray new];
> [vcArr addObject:[[MJGoTableViewController alloc]init]];
> [vcArr addObject:[[MJGoApplyTableViewController alloc]init]];
> 
> 
> WMZPageParam *param = PageParam()
> .wTitleArrSet(data)
> .wMenuTitleOffsetSet(16.5*MJSCALE)
> .wMenuTitleSelectColorSet(UIColorWhite)
> .wMenuTitleColorSet(UIColorWithHexString(@"#FFFFFF"))
> .wMenuAnimalSet(3)
> .wMenuIndicatorWidthSet(28*MJSCALE)
> .wMenuCellMarginSet(16.5*MJSCALE)
> .wMenuBgColorSet(UIColorWithHexString(@"#4B4B4B"))
> .wMenuCellMarginYSet(20*MJSCALEH)
> .wFromNaviSet(NO)
> .wControllersSet(vcArr);
> self.param = param;
> ```
