### ISSUE TITLE
在iPad上转屏会有问题

### ISSUE THREAD

**Issue by SunBoyXiao** [wwmz/WMZPageController#63]
使用WMZPageController框架，在iPad上横竖屏切换，横屏的时候无法铺满满屏。

**Comment by wwmz** [comment]
目前不支持转屏哦 还没适配



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MinFang ***@***.***&gt;
发送时间: 2021年11月20日 14:59
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63)

**Comment by SunBoyXiao** [comment]
> 目前不支持转屏哦 还没适配 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MinFang ***@***.***&gt; 发送时间: 2021年11月20日 14:59 收件人: wwmz/WMZPageController ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63)

在继承WMZPageController的子控制器中加入：
- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];
    [self updatePageController];
}
横竖屏倒是可以，但是是重新渲染的页面。

**Comment by wwmz** [comment]
是的 这样会全部重新渲染的&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MinFang ***@***.***&gt;
发送时间: 2021年11月20日 15:03
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63)





  
目前不支持转屏哦 还没适配 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: MinFang @.&gt; 发送时间: 2021年11月20日 14:59 收件人: wwmz/WMZPageController @.&gt; 抄送: Subscribed @.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63)
  
在继承WMZPageController的子控制器中加入：
  
(void)viewWillLayoutSubviews {
 [super viewWillLayoutSubviews];
 [self updatePageController];
 }
 横竖屏倒是可以，但是是重新渲染的页面。 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SunBoyXiao** [comment]
> 是的 这样会全部重新渲染的&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MinFang ***@***.***&gt; 发送时间: 2021年11月20日 15:03 收件人: wwmz/WMZPageController ***@***.***&gt; 抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 目前不支持转屏哦 还没适配 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: MinFang @.&gt; 发送时间: 2021年11月20日 14:59 收件人: wwmz/WMZPageController @.&gt; 抄送: Subscribed @.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 在继承WMZPageController的子控制器中加入： (void)viewWillLayoutSubviews { [super viewWillLayoutSubviews]; [self updatePageController]; } 横竖屏倒是可以，但是是重新渲染的页面。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SunBoyXiao** [comment]
> 是的 这样会全部重新渲染的&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: MinFang ***@***.***&gt; 发送时间: 2021年11月20日 15:03 收件人: wwmz/WMZPageController ***@***.***&gt; 抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 目前不支持转屏哦 还没适配 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: MinFang @.&gt; 发送时间: 2021年11月20日 14:59 收件人: wwmz/WMZPageController @.&gt; 抄送: Subscribed @.***&gt; 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 在继承WMZPageController的子控制器中加入： (void)viewWillLayoutSubviews { [super viewWillLayoutSubviews]; [self updatePageController]; } 横竖屏倒是可以，但是是重新渲染的页面。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

大佬，WMZPageController框架有支持横竖的计划没？

**Comment by wwmz** [comment]
> > 是的 这样会全部重新渲染的  发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: MinFang _**@**_._**> 发送时间: 2021年11月20日 15:03 收件人: wwmz/WMZPageController _**@**_.**_> 抄送: WMZ _**@**_._**>, Comment _**@**_.**_> 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 目前不支持转屏哦 还没适配 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: MinFang @.> 发送时间: 2021年11月20日 14:59 收件人: wwmz/WMZPageController @.> 抄送: Subscribed @.***> 主题: Re: [wwmz/WMZPageController] 在iPad上转屏会有问题 (Issue #63) 在继承WMZPageController的子控制器中加入： (void)viewWillLayoutSubviews { [super viewWillLayoutSubviews]; [self updatePageController]; } 横竖屏倒是可以，但是是重新渲染的页面。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 大佬，WMZPageController框架有支持横竖的计划没？

后面有时间会加入

**Comment by wwmz** [comment]
1.5.1支持横竖斜 wDeviceChange （default NO）
