### ISSUE TITLE
请问怎么修改MenuView的圆角？

### ISSUE THREAD

**Issue by 542604974** [wwmz/WMZPageController#64]
<img width="308" alt="截屏2021-11-22 下午5 05 46" src="https://user-images.githubusercontent.com/15099430/142833049-a9b8a695-90e9-4bba-afe9-883f7497d20f.png">

**Comment by wwmz** [comment]
> <img alt="截屏2021-11-22 下午5 05 46" width="308" src="https://user-images.githubusercontent.com/15099430/142833049-a9b8a695-90e9-4bba-afe9-883f7497d20f.png">
wBgColor可以设置背景颜色 
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
          /// 使用 self.upSc.mainView 设置圆角代码      
    });

**Comment by 542604974** [comment]
改了没反应。

**Comment by wwmz** [comment]
> 改了没反应。

贴代码  wBgColor设置个红色啥的看一下

**Comment by 542604974** [comment]
可以了，哈哈，因为背景白色看不出来，谢了
