### ISSUE TITLE
WMPageController

### ISSUE THREAD

**Issue by lilin87788** [wwmz/WMZPageController#65]
WMPageController 和 WMZPageController  有关联吗，我一直用的WMPageController，后面断更了，以为作者不维护了，后面准备用JXPage,但是用的不是很顺手

**Comment by wwmz** [comment]
> WMPageController 和 WMZPageController 有关联吗，我一直用的WMPageController，后面断更了，以为作者不维护了，后面准备用JXPage,但是用的不是很顺手

没有关联 ~ ~ 不是同个人哈
