### ISSUE TITLE
请问如何修改分页载屏幕上的位置

### ISSUE THREAD

**Issue by JunCheng312** [wwmz/WMZPageController#67]
比如我想把分页控制在屏幕的某个位置

**Comment by wwmz** [comment]
> 比如我想把分页控制在屏幕的某个位置

这个的话目前只能作为整体使用 里面可以设置dataSource和headView 理论上可以实现任何页面的  下一版本抽出来后才可以控制在任意位置使用

**Comment by wwmz** [comment]
1.5.0 支持
