### ISSUE TITLE
设置了选中颜色之后，滑动切换之后，颜色不对。

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZPageController#68]
.wTitleArrSet(weakSelf.titleArray)
    .wMenuAnimalSet(PageTitleMenuAiQY)
    .wMenuDefaultIndexSet(0)
    .wMenuTitleWidthSet(ScreenWidth/3)
    .wMenuBgColorSet([UIColor blackColor])
    .wMenuTitleColorSet([[UIColor whiteColor] colorWithAlphaComponent:0.3])
    .wMenuTitleSelectColorSet([UIColor whiteColor])
    .wMenuTitleUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
    .wMenuTitleSelectUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
    .wMenuHeightSet(SBRealValue(40))
    .wAvoidQuickScrollSet(YES)
    .wTopSuspensionSet(YES)
    .wFromNaviSet(NO)

数组里面的标题是三个，如此设置之后，通过滑动到第二个标题的时候，第三个标题的颜色也变成了白色，而且是不管我SelectColor设置成什么颜色，滑动到第二个标题的时候，第三个标题都会变成白色

**Comment by wwmz** [comment]
> ```
> .wTitleArrSet(weakSelf.titleArray)
> .wMenuAnimalSet(PageTitleMenuAiQY)
> .wMenuDefaultIndexSet(0)
> .wMenuTitleWidthSet(ScreenWidth/3)
> .wMenuBgColorSet([UIColor blackColor])
> .wMenuTitleColorSet([[UIColor whiteColor] colorWithAlphaComponent:0.3])
> .wMenuTitleSelectColorSet([UIColor whiteColor])
> .wMenuTitleUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuTitleSelectUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuHeightSet(SBRealValue(40))
> .wAvoidQuickScrollSet(YES)
> .wTopSuspensionSet(YES)
> .wFromNaviSet(NO)
> ```
> 
> 数组里面的标题是三个，如此设置之后，通过滑动到第二个标题的时候，第三个标题的颜色也变成了白色，而且是不管我SelectColor设置成什么颜色，滑动到第二个标题的时候，第三个标题都会变成白色

wTitleArrSet里是不是设置了颜色？

**Comment by wwmz** [comment]
> ```
> .wTitleArrSet(weakSelf.titleArray)
> .wMenuAnimalSet(PageTitleMenuAiQY)
> .wMenuDefaultIndexSet(0)
> .wMenuTitleWidthSet(ScreenWidth/3)
> .wMenuBgColorSet([UIColor blackColor])
> .wMenuTitleColorSet([[UIColor whiteColor] colorWithAlphaComponent:0.3])
> .wMenuTitleSelectColorSet([UIColor whiteColor])
> .wMenuTitleUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuTitleSelectUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuHeightSet(SBRealValue(40))
> .wAvoidQuickScrollSet(YES)
> .wTopSuspensionSet(YES)
> .wFromNaviSet(NO)
> ```
> 
> 数组里面的标题是三个，如此设置之后，通过滑动到第二个标题的时候，第三个标题的颜色也变成了白色，而且是不管我SelectColor设置成什么颜色，滑动到第二个标题的时候，第三个标题都会变成白色

我看了一下 是wMenuAnimalTitleGradient 渐变的时候对于透明度有点问题 你把这个属性设为NO就好了

**Comment by wwmz** [comment]
> > ```
> > .wTitleArrSet(weakSelf.titleArray)
> > .wMenuAnimalSet(PageTitleMenuAiQY)
> > .wMenuDefaultIndexSet(0)
> > .wMenuTitleWidthSet(ScreenWidth/3)
> > .wMenuBgColorSet([UIColor blackColor])
> > .wMenuTitleColorSet([[UIColor whiteColor] colorWithAlphaComponent:0.3])
> > .wMenuTitleSelectColorSet([UIColor whiteColor])
> > .wMenuTitleUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> > .wMenuTitleSelectUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> > .wMenuHeightSet(SBRealValue(40))
> > .wAvoidQuickScrollSet(YES)
> > .wTopSuspensionSet(YES)
> > .wFromNaviSet(NO)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 数组里面的标题是三个，如此设置之后，通过滑动到第二个标题的时候，第三个标题的颜色也变成了白色，而且是不管我SelectColor设置成什么颜色，滑动到第二个标题的时候，第三个标题都会变成白色
> 
> 我看了一下 是wMenuAnimalTitleGradient 渐变的时候对于透明度有点问题 你把这个属性设为NO就好了

> ```
> .wTitleArrSet(weakSelf.titleArray)
> .wMenuAnimalSet(PageTitleMenuAiQY)
> .wMenuDefaultIndexSet(0)
> .wMenuTitleWidthSet(ScreenWidth/3)
> .wMenuBgColorSet([UIColor blackColor])
> .wMenuTitleColorSet([[UIColor whiteColor] colorWithAlphaComponent:0.3])
> .wMenuTitleSelectColorSet([UIColor whiteColor])
> .wMenuTitleUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuTitleSelectUIFontSet([UIFont systemFontOfSize:SBRealValue(14)])
> .wMenuHeightSet(SBRealValue(40))
> .wAvoidQuickScrollSet(YES)
> .wTopSuspensionSet(YES)
> .wFromNaviSet(NO)
> ```
> 
> 数组里面的标题是三个，如此设置之后，通过滑动到第二个标题的时候，第三个标题的颜色也变成了白色，而且是不管我SelectColor设置成什么颜色，滑动到第二个标题的时候，第三个标题都会变成白色

下版本修复这个问题 你这个版本把渐变关了就正常了

**Comment by maoweipengft** [comment]
好的
