### ISSUE TITLE
隐藏导航栏后，直接把菜单栏加到导航栏的位置，页面下部分有留白，大概一个导航栏的高度，具体代码在这里

### ISSUE THREAD

**Issue by miaojia** [wwmz/WMZPageController#7]
NSArray *data=@[@"活动行程",@"申请记录"];

NSMutableArray *vcArr=[NSMutableArray new];
[vcArr addObject:[[MJGoTableViewController alloc]init]];
[vcArr addObject:[[MJGoApplyTableViewController alloc]init]];

WMZPageParam *param = PageParam()
.wTitleArrSet(data)
.wMenuTitleOffsetSet(16.5)
.wMenuTitleSelectColorSet(UIColorWhite)
.wMenuTitleColorSet(UIColorWithHexString(@"#FFFFFF"))
.wMenuAnimalSet(3)
.wMenuIndicatorWidthSet(28)
.wMenuCellMarginSet(16.5)
.wMenuBgColorSet(UIColorWithHexString(@"#4B4B4B"))
.wMenuCellMarginYSet(20)
.wFromNaviSet(NO)
.wControllersSet(vcArr);
self.param = param;

self.rectArr=[NSMutableArray new];
CGRect frame=CGRectMake(SCREEN_WIDTH*vcArr.count, 0, SCREEN_WIDTH, SCREEN_HEIGHT-TabBarHeight);
[self.rectArr addObject:[NSValue valueWithCGRect:frame]];

**Comment by miaojia** [comment]
大神能留个联系方式吗

**Comment by wwmz** [comment]
925457662

**Comment by SiliconZou** [comment]
大神 同样遇到了这个问题 要怎么解决呢 @wwmz
