### ISSUE TITLE
放在首页时，滚动后高度不正确

### ISSUE THREAD

**Issue by liufengting** [wwmz/WMZPageController#70]
放在首页时，滚动后高度不正确

```
    lazy var params: WMZPageParam = {
        let p = WMZPageParam()
        p.wTitleArr = self.titles
        p.wBgColor = .systemBackground
        p.wMenuBgColor = .systemBackground
        p.wMenuTitleSelectColor = .label
        p.wMenuTitleColor = .secondaryLabel
        p.wMenuIndicatorColor = .label
        p.wMenuTitleUIFont = UIFont.systemFont(ofSize: 17, weight: .bold)
        p.wMenuTitleSelectUIFont = UIFont.systemFont(ofSize: 17, weight: .bold)
        p.wMenuAnimal = PageTitleMenuPDD
        p.wFromNavi = true
        p.wMenuHeight = 50
        p.wMenuPosition = PageMenuPositionCenter
        p.wTopSuspension = true
        p.wLazyLoading = true
        p.wViewController = { index in
            if index == 0 {
                return self.highlightVC
            }
            return self.activityVC
        }
        p.wMenuHeadView = {
            return self.header
        }
        return p
    }()
```

![IMG_3463](https://user-images.githubusercontent.com/4414522/147630130-f54b4d8c-6cb5-42e2-9abc-2c4bf70987cf.PNG)

**Comment by wwmz** [comment]
> 放在首页时，滚动后高度不正确
> 
> ```
>     lazy var params: WMZPageParam = {
>         let p = WMZPageParam()
>         p.wTitleArr = self.titles
>         p.wBgColor = .systemBackground
>         p.wMenuBgColor = .systemBackground
>         p.wMenuTitleSelectColor = .label
>         p.wMenuTitleColor = .secondaryLabel
>         p.wMenuIndicatorColor = .label
>         p.wMenuTitleUIFont = UIFont.systemFont(ofSize: 17, weight: .bold)
>         p.wMenuTitleSelectUIFont = UIFont.systemFont(ofSize: 17, weight: .bold)
>         p.wMenuAnimal = PageTitleMenuPDD
>         p.wFromNavi = true
>         p.wMenuHeight = 50
>         p.wMenuPosition = PageMenuPositionCenter
>         p.wTopSuspension = true
>         p.wLazyLoading = true
>         p.wViewController = { index in
>             if index == 0 {
>                 return self.highlightVC
>             }
>             return self.activityVC
>         }
>         p.wMenuHeadView = {
>             return self.header
>         }
>         return p
>     }()
> ```
> 
> ![IMG_3463](https://user-images.githubusercontent.com/4414522/147630130-f54b4d8c-6cb5-42e2-9abc-2c4bf70987cf.PNG)

你这应该是底部减多了个tabbar的距离 wcustomTabbar 调一下

**Comment by liufengting** [comment]
```
        p.wCustomTabbarY = { _ in
            return 0
        }
```

上面的代码可以解决。
