### ISSUE TITLE
请问子控制器里面需要侧滑 怎么解决？

### ISSUE THREAD

**Issue by xhr4469** [wwmz/WMZPageController#71]
请问子控制器里面需要侧滑 怎么解决？

**Comment by wwmz** [comment]
> 请问子控制器里面需要侧滑 怎么解决？

wRespondGuestureType  响应侧滑或者全屏返回手势 default PagePopFirst

**Comment by xhr4469** [comment]
能在demo里面加一个例子吗？谢谢

**Comment by wwmz** [comment]
Demo有例子啊。。。这是个枚举 &nbsp;对应首个响应 全部响应 不响应



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xhr4469 ***@***.***&gt;
发送时间: 2022年1月12日 14:10
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 请问子控制器里面需要侧滑 怎么解决？ (Issue #71)





 
能在demo里面加一个例子吗？谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xhr4469** [comment]
那个枚举  木有发现呢 亲。请你轻轻的告诉我

**Comment by wwmz** [comment]
> wRespondGuestureType

wRespondGuestureType我上面不是发了吗 你没看到吗 没有的话你就更新一下版本 1.4.1后才有

**Comment by xhr4469** [comment]
全部响应 首个响应 不响应 我都点了 在 TestVC里面添加了侧滑功能，侧滑还是无效

//先要设Cell可编辑
- (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
  return YES;
}
//定义编辑样式
- (UITableViewCellEditingStyle)tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath {
 return UITableViewCellEditingStyleDelete;
}

//修改编辑按钮文字
- (NSString *)tableView:(UITableView *)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)indexPath {
    return @"删除";
}

//设置进入编辑状态时，Cell不会缩进
- (BOOL)tableView: (UITableView *)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath *)indexPath {
   return NO;

}

//点击删除
- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
  
}

**Comment by xhr4469** [comment]
有时候能侧滑，很少有时候能侧滑出 删除 哈哈哈

**Comment by wwmz** [comment]
> 全部响应 首个响应 不响应 我都点了 在 TestVC里面添加了侧滑功能，侧滑还是无效
> 
> //先要设Cell可编辑
> 
> * (BOOL)tableView:(UITableView *)tableView canEditRowAtIndexPath:(NSIndexPath *)indexPath {
>   return YES;
>   }
>   //定义编辑样式
> * (UITableViewCellEditingStyle)tableView:(UITableView *)tableView editingStyleForRowAtIndexPath:(NSIndexPath *)indexPath {
>   return UITableViewCellEditingStyleDelete;
>   }
> 
> //修改编辑按钮文字
> 
> * (NSString *)tableView:(UITableView *)tableView titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)indexPath {
>   return @"删除";
>   }
> 
> //设置进入编辑状态时，Cell不会缩进
> 
> * (BOOL)tableView: (UITableView *)tableView shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath *)indexPath {
>   return NO;
> 
> }
> 
> //点击删除
> 
> * (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {
> 
> }

= =你这说的是左滑删除吧。。。。 亲侧滑和左滑区分一下吧 我以为你说的侧滑返回。..。。。 这个没办法哦区分不了 你要左滑 只能把滑动的手势关了wScrollCanTransfer设为NO

**Comment by xhr4469** [comment]
好的 哈哈哈 谢谢
