### ISSUE TITLE
请问header可以修改高度吗？

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZPageController#73]
我想修改header的高度 
self.headerPerView.size = CGSizeMake(ScreenWidth, 600);
[self updateHeadView];
这样做并没有起效果，请问一下支持动态修改header的高度吗

**Comment by wwmz** [comment]
> 我想修改header的高度 self.headerPerView.size = CGSizeMake(ScreenWidth, 600); [self updateHeadView]; 这样做并没有起效果，请问一下支持动态修改header的高度吗

要重新设置 wMenuHeadViewSet 然后再调用updateHeadView 即可 demo有例子  我字还没打完你已经关闭了issuse了 哦豁
