### ISSUE TITLE
请问wTopSuspensionSet只能初始化的时候设置吗？

### ISSUE THREAD

**Issue by MasterWen** [wwmz/WMZPageController#75]
请问wTopSuspensionSet只能初始化的时候设置吗？我想后面更改这个属性但是不生效。或者我可以设置哪个属性让标题固定一个位置不跟随滑动

**Comment by wwmz** [comment]
> 请问wTopSuspensionSet只能初始化的时候设置吗？我想后面更改这个属性但是不生效。或者我可以设置哪个属性让标题固定一个位置不跟随滑动

使用 WMZPageView可设置任意位置

**Comment by MasterWen** [comment]
wTopSuspensionSet(NO)当这个属性设置成NO时，下面的滚动视图滚动时底部会有一部分被遮挡

**Comment by wwmz** [comment]
> wTopSuspensionSet(NO)当这个属性设置成NO时，下面的滚动视图滚动时底部会有一部分被遮挡

这个自己调整一下就好了 wCustomTabbarY 那块的属性
