### ISSUE TITLE
#import "WMZPageMenuView.h"

### ISSUE THREAD

**Issue by weweMM** [wwmz/WMZPageController#79]
导入#import "WMZPageMenuView.h" 报错啊 
想单独使用 menuview 结果导入报错 这个应该怎么导入那

**Comment by wwmz** [comment]
报错什么



发自我的iPhone


------------------ Original ------------------
From: wewe ***@***.***&gt;
Date: Tue,Mar 15,2022 3:25 PM
To: wwmz/WMZPageController ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [wwmz/WMZPageController] #import "WMZPageMenuView.h" (Issue #79)

**Comment by wwmz** [comment]
> 导入#import "WMZPageMenuView.h" 报错啊 想单独使用 menuview 结果导入报错 这个应该怎么导入那

目前我版本是没问题的 你可以更新到最新版本哈
