### ISSUE TITLE
建议设置按钮图片时判断是否时网络图

### ISSUE THREAD

**Issue by sophty** [wwmz/WMZPageController#8]
175行：CGSize size =  btn.maxSize;
   //设置图片
     id image = [self getTitleData:self.param.wTitleArr[i] key:@"image"];
     id selectImage = [self getTitleData:self.param.wTitleArr[i] key:@"selectImage"];
     if (image) {
[btn sd_setImageWithURL:[NSURL URLWithString:image] forState:UIControlStateNormal];

**Comment by wwmz** [comment]
> 175行：CGSize size = btn.maxSize;
> //设置图片
> id image = [self getTitleData:self.param.wTitleArr[i] key:@"image"];
> id selectImage = [self getTitleData:self.param.wTitleArr[i] key:@"selectImage"];
> if (image) {
> [btn sd_setImageWithURL:[NSURL URLWithString:image] forState:UIControlStateNormal];

可以 下个版本加上

**Comment by wwmz** [comment]
> [self getTitleData:self.param.wTitleArr[i] key:@"image"]

可以尝试在自定义标题的方法里 修改的 由于不想引用sd_image这个库 我就不加上去了
.wCustomMenuTitleSet(^(NSArray *titleArr) {
            [titleArr enumerateObjectsUsingBlock:^(WMZPageNaviBtn*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                [btn sd_setImageWithURL:[NSURL URLWithString:image] forState:UIControlStateNormal];
            }];
        })
