### ISSUE TITLE
开启悬浮wTopSuspensionSet

### ISSUE THREAD

**Issue by hardworkz** [wwmz/WMZPageController#80]
父控制器开启悬浮wTopSuspensionSet，子控制器的悬浮菜单栏悬停就会失效，如果要实现父控制器头部动画效果需要监听wEventChildVCDidSrollSet，则子控制器的监听wEventChildVCDidSrollSet block方法就会失效，子分页控制器的header会一直停留在头部

**Comment by wwmz** [comment]
啥意思呢。。这个我听的有点懵&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hardworkz ***@***.***&gt;
发送时间: 2022年3月22日 16:02
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 开启悬浮wTopSuspensionSet (Issue #80)





 
父控制器开启悬浮wTopSuspensionSet，子控制器的悬浮菜单栏悬停就会失效，如果要实现父控制器头部动画效果需要监听wEventChildVCDidSrollSet，则子控制器的监听wEventChildVCDidSrollSet block方法就会失效，子分页控制器的header会一直停留在头部

**Comment by wwmz** [comment]
> 父控制器开启悬浮wTopSuspensionSet，子控制器的悬浮菜单栏悬停就会失效，如果要实现父控制器头部动画效果需要监听wEventChildVCDidSrollSet，则子控制器的监听wEventChildVCDidSrollSet block方法就会失效，子分页控制器的header会一直停留在头部

你说的是二级嵌套吗？？？

**Comment by hardworkz** [comment]
对的，一级的头部区域我会监听同时进行动画交互，开启悬停，二级的头部区域我也会开启悬停，目前这种场景只能有一个监听生效

**Comment by wwmz** [comment]
两个地方都悬停？有这种交互吗 你看一下我三级嵌套里面&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hardworkz ***@***.***&gt;
发送时间: 2022年3月22日 18:15
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 开启悬浮wTopSuspensionSet (Issue #80)

**Comment by hardworkz** [comment]
你的三级嵌套里面的二级和三级都没有设置header  .wMenuHeadViewSet，如果有header那肯定需要让菜单栏悬停到头部消失时的位置，这样才能保证界面的内容连接

**Comment by wwmz** [comment]
> 你的三级嵌套里面的二级和三级都没有设置header .wMenuHeadViewSet，如果有header那肯定需要让菜单栏悬停到头部消失时的位置，这样才能保证界面的内容连接

父视图开启wTopSuspensionSet的时候子视图也要开启 你试试 我也不知道你这个目前什么问题 可以加q我看看

**Comment by hardworkz** [comment]
好的，我没找到你q，我的qq：1138113194，麻烦了作者大大

**Comment by hardworkz** [comment]
另一个一个问题，我发现二级嵌套的分页控制器无法设置头部刷新，我在您提供的Demo里面进行设置同样是失效的：微博嵌套(导航栏+二级)中的WeiBoSonController控制器设置self.downSc.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{ }];下拉并未出现头部刷新组件

**Comment by hardworkz** [comment]
针对【另一个问题，我发现二级嵌套的分页控制器无法设置头部刷新，我在您提供的Demo里面进行设置同样是失效的：微博嵌套(导航栏+二级)中的WeiBoSonController控制器设置self.downSc.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{ }];下拉并未出现头部刷新组件】这个问题 ,二级结构中我在子分页控制器使用UIViewController+WMZPageView可以解决无下拉刷新组件的问题

**Comment by wwmz** [comment]
> 针对【另一个问题，我发现二级嵌套的分页控制器无法设置头部刷新，我在您提供的Demo里面进行设置同样是失效的：微博嵌套(导航栏+二级)中的WeiBoSonController控制器设置self.downSc.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{ }];下拉并未出现头部刷新组件】这个问题 ,二级结构中我在子分页控制器使用UIViewController+WMZPageView可以解决无下拉刷新组件的问题

二级嵌套的话 没有一级那么灵活哈 我q 925457662
