### ISSUE TITLE
怎么让，menu view在 不满一屏的情况下可以滑动

### ISSUE THREAD

**Issue by flyuqian** [wwmz/WMZPageController#81]

**Comment by flyuqian** [comment]
怎么让，menu view再 不满一屏的情况下可以滑动

**Comment by wwmz** [comment]
不满一屏没法滑动吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: flyuqian ***@***.***&gt;
发送时间: 2022年4月2日 14:39
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 怎么让menu vuew (Issue #81)

**Comment by flyuqian** [comment]
> 不满一屏没法滑动吧 发自我的iPhone
> […](#)

我想让他滑动，我设置 content size 也没效果；self.upSc.mainView.contentSize = CGSizeMake(screenW+1, 0);

**Comment by wwmz** [comment]
> > 不满一屏没法滑动吧 发自我的iPhone
> > […](#)
> 
> 我想让他滑动，我设置 content size 也没效果；self.upSc.mainView.contentSize = CGSizeMake(screenW+1, 0);

你延迟个0.5秒加载这段代码就可以
