### ISSUE TITLE
希望添加类似腾讯新闻的效果

### ISSUE THREAD

**Issue by DockLle** [wwmz/WMZPageController#83]
左右滑动相关的两个标题会相应的放大缩小，并且后面标题的位置可能会随着两个标题的缩放有位置变动

**Comment by wwmz** [comment]
> 左右滑动相关的两个标题会相应的放大缩小，并且后面标题的位置可能会随着两个标题的缩放有位置变动

效果图呢 给个动画图看看

**Comment by DockLle** [comment]
你用下载腾讯新闻，找个长一点的标题，亲手试一下应该更容易清楚效果

**Comment by wwmz** [comment]
新增 wMenuAnimalTitleScale
