### ISSUE TITLE
初始化时无数据时

### ISSUE THREAD

**Issue by DockLle** [wwmz/WMZPageController#84]
初始化无title和controller,  然后给param设置数据，再updateMenuData，在有wMenuAddSubViewSet的情况下，布局有问题，在添加了背景的情况下，背景没了
![IMG_3843](https://user-images.githubusercontent.com/11973456/170964435-86e6cabf-7e9f-4fd5-8b81-6f2cbda04149.JPG)
![IMG_3842](https://user-images.githubusercontent.com/11973456/170964577-9e370a6f-ecd9-4921-9e87-95e5e17bf25b.JPG)

**Comment by wwmz** [comment]
已修复v1.5.3
