### ISSUE TITLE
在tableViewCell里面使用WMZapgeView 无法加载出需要加载的view。

### ISSUE THREAD

**Issue by DanDanXiaoMu** [wwmz/WMZPageController#85]
不知道是我使用有误，还是这个库不支持。在cell中添加后无法显示要加载的ViewController

**Comment by wwmz** [comment]
。。。什么样的需求 需要在cell里使用啊&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DanDanXiaoMu ***@***.***&gt;
发送时间: 2022年6月9日 16:59
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 在tableViewCell里面使用WMZapgeView 无法加载出需要加载的view。 (Issue #85)





 
不知道是我使用有误，还是这个库不支持。在cell中添加后无法显示要加载的ViewController

**Comment by wwmz** [comment]
responseer需要传入当前所在的ViewController
