### ISSUE TITLE
各个板块中放UITableView的问题

### ISSUE THREAD

**Issue by 624990742** [wwmz/WMZPageController#9]
1.在导航栏透明度变化+头部刷新这个demo中，如果我在各个板块控制器内添加UITableView，会出现UITableView下拉的时候，头部就会立马下拉刷新的问题。应该是手势处理的问题。
2.在导航栏透明度变化+头部刷新这个demo中，无法添加加载更多。

**Comment by wwmz** [comment]
> 1.在导航栏透明度变化+头部刷新这个demo中，如果我在各个板块控制器内添加UITableView，会出现UITableView下拉的时候，头部就会立马下拉刷新的问题。应该是手势处理的问题。
> 2.在导航栏透明度变化+头部刷新这个demo中，无法添加加载更多。

1 的话我没重现到 你看我demo能重现吗 
2 你说的添加加载更多我demo不是有吗 你是怎么加的 可以加我q(925457662)发个视频给我看看
