### ISSUE TITLE
导航栏title消失；底部空白一块

### ISSUE THREAD

**Issue by zgGitHub** [wwmz/WMZPageController#90]
你好，在从横屏的全屏视频播放页面返回来的时候，会出现顶部导航栏的title消失不见，而且底部会多出来一段大概tabbar高度的空白；

我使用的是继承WMZPageController;查看UI发现 PageView高度是正常的，WMZPageScroller底部有空白，WMZPageLoopView 又多出来一段空白；

**Comment by wwmz** [comment]
可以暂时把横竖屏适配关闭哦 wDeviceChange 为NO默认是true



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jimsir ***@***.***&gt;
发送时间: 2022年7月14日 10:02
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] 导航栏title消失；底部空白一块 (Issue #90)

**Comment by zgGitHub** [comment]
嗯，我关闭横竖屏的话确实是不会出现上述问题了
