### ISSUE TITLE
从pageVC中的scroll瞬间滑动到顶部

### ISSUE THREAD

**Issue by XcodeLiubo** [wwmz/WMZPageController#91]
有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时,  交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的

**Comment by wwmz** [comment]
> 有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时, 交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的

wAvoidQuickScroll 试一试开启这个属性呢 默认是NO

**Comment by XcodeLiubo** [comment]
这个我是开启了的, 还是这个问题, 补充一下, 如果子vc下的scrollview有偏移的话(即使很小), 没有这种现象

**Comment by XcodeLiubo** [comment]
> > 有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时, 交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的
> 
> wAvoidQuickScroll 试一试开启这个属性呢 默认是NO


这个我是开启了的, 还是这个问题, 补充一下, 如果子vc下的scrollview有偏移的话(即使很小), 没有这种现象

**Comment by wwmz** [comment]
> > > 有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时, 交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的
> > 
> > 
> > wAvoidQuickScroll 试一试开启这个属性呢 默认是NO
> 
> 这个我是开启了的, 还是这个问题, 补充一下, 如果子vc下的scrollview有偏移的话(即使很小), 没有这种现象

录个视频看看

**Comment by XcodeLiubo** [comment]
你给个邮箱, 或者交流群什么的, 我发你, 有点大

**Comment by XcodeLiubo** [comment]
> > > > 有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时, 交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的
> > > 
> > > 
> > > wAvoidQuickScroll 试一试开启这个属性呢 默认是NO
> > 
> > 
> > 这个我是开启了的, 还是这个问题, 补充一下, 如果子vc下的scrollview有偏移的话(即使很小), 没有这种现象
> 
> 录个视频看看

给个邮箱什么的, 我发一下

**Comment by wwmz** [comment]
> > > > > 有一种情况是, 手从子vc下的scrollview, 突然上滑, 使框架内的最底层的scrollview联动到顶部(off_y ==0)时, 交互消失(子vc下的scrollview没有惯性继续往 off_y > 0的方向上自动滑动), 必须抬起手, 再滑动子vc下的scrollview. 这种情况出现的概率还是比较高的
> > > > 
> > > > 
> > > > wAvoidQuickScroll 试一试开启这个属性呢 默认是NO
> > > 
> > > 
> > > 这个我是开启了的, 还是这个问题, 补充一下, 如果子vc下的scrollview有偏移的话(即使很小), 没有这种现象
> > 
> > 
> > 录个视频看看
> 
> 给个邮箱什么的, 我发一下

925457662@qq.com

**Comment by wwmz** [comment]
最新版本看看呢
