### ISSUE TITLE
paegRemoveObserver  这个paeg方便的话可以改一下page

### ISSUE THREAD

**Issue by zgGitHub** [wwmz/WMZPageController#92]
///  安全删除观察者
- (void)paegRemoveObserver:(nonnull NSObject *)observer forKeyPath:(nonnull NSString *)keyPath context:(nullable void *)context;

**Comment by wwmz** [comment]
> /// 安全删除观察者
> 
> * (void)paegRemoveObserver:(nonnull NSObject *)observer forKeyPath:(nonnull NSString *)keyPath context:(nullable void *)context;

😄
