### ISSUE TITLE
WMZPageView 背景色如何透明

### ISSUE THREAD

**Issue by qianciling** [wwmz/WMZPageController#93]
看代码setupUI 中直接设置了self.backgroundColor = UIColor.whiteColor;
修改WMZPageParam中wBgColor = clear无效

**Comment by wwmz** [comment]
> 看代码setupUI 中直接设置了self.backgroundColor = UIColor.whiteColor; 修改WMZPageParam中wBgColor = clear无效

直接修改wmzpageView就好啦   wBgColor 是设置upSc的
