### ISSUE TITLE
WMZUsePageVC的cell高度无法自适应

### ISSUE THREAD

**Issue by XiaoPangTang** [wwmz/WMZPageController#96]
demo "实现tableviewDataSource协议写复杂UI"  ——>  WMZUsePageVC
可否实现上下两个tableView的cell高度自适应呢

**Comment by wwmz** [comment]
> WMZUsePageVC

你说的是tableviewcell的自适应？可以的啊 设置好约束

**Comment by Lpkiki** [comment]
也是这个页面 ，[self.pageView.downSc reloadData ] ,不执行 heightForRowAtIndexPath ,  怎么能让它主动走代理啊

**Comment by Lpkiki** [comment]
我是单独使用的 WMZPageView ，heightForRowAtIndexPath 就不执行， 继承的 VC 没问题

**Comment by wwmz** [comment]
设置一下downSc 的datasource



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LPBezierView ***@***.***&gt;
发送时间: 2024年1月8日 14:19
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] WMZUsePageVC的cell高度无法自适应 (Issue #96)





 
也是这个页面 ，[self.pageView.downSc reloadData ] ,不执行 heightForRowAtIndexPath ,  怎么能让它主动走代理啊

**Comment by Lpkiki** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Lpkiki** [comment]
你好 我找到原因，WMZPageView的datasource 我已经设置了，也在自己的VC 里面设置了delegate，请求到数据后我更新了分类 self.param.wTitleArr = @[@"分类1",@"分类2"] 调用了 [self.pageView updateMenuData];   WMZPageView的updateMenuData 会调用setUpUI ，setUpUI 有一行代码：
  
 
    if ([self.parentResponder isKindOfClass:WMZPageController.class]) {
        self.downSc.delegate = (id)self.parentResponder;
    }else{
        self.downSc.delegate = self;
    }
    
    然后 发现downSc 的delegate被重置了，导致自己的VC里面 无法执行 heightForRowAtIndexPath  
    
    
    我现在 在调用 [self.pageView updateMenuData] 的代码后面 再把WMZPageView 的delegate 设置一下 ： self.pageView.downSc.delegate = self;
        [self.pageView.downSc reloadData ];
        
        这样就可以刷新  自定义Cell 的高度了，
