### ISSUE TITLE
wMenuHeadView 高度如何自适应？

### ISSUE THREAD

**Issue by yangxuefei18** [wwmz/WMZPageController#97]
wMenuHeadView 高度如何自适应？ 例如HeadView里有个按钮，点击展开，查看所有文字

**Comment by wwmz** [comment]
> wMenuHeadView 高度如何自适应？ 例如HeadView里有个按钮，点击展开，查看所有文字
自适应不了 wMenuHeadView里返回的uiview手动改变frame 然后调用updateHeadView

**Comment by wwmz** [comment]
设置wahead 然后调用updatehead



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangxuefei18 ***@***.***&gt;
发送时间: 2022年8月30日 13:37
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] wMenuHeadView 高度如何自适应？ (Issue #97)
