### ISSUE TITLE
WMZPageView KVO 崩溃

### ISSUE THREAD

**Issue by graceydb** [wwmz/WMZPageController#99]
[WMZPageView observeValueForKeyPath:ofObject:change:context:] 要崩溃，崩溃概率很大，一直没找到是什么操作导致的；
而且嵌套的滚动视图实现了getMyScrollView协议之后，偶尔也会出现到顶之后还可以向下滑动的问题

**Comment by wwmz** [comment]
崩溃版本是多少呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yoon ***@***.***&gt;
发送时间: 2022年9月21日 16:28
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] WMZPageView KVO 崩溃 (Issue #99)

**Comment by graceydb** [comment]
@wwmz 我是下载拖进项目的，大概是5月底的版本；崩溃在这里：EXC_BAD_ACCESS；
![1663749548621](https://user-images.githubusercontent.com/2683784/191457556-f107b788-425d-4a82-b072-ac6b00327eb3.jpg)

**Comment by wwmz** [comment]
> @wwmz 我是下载拖进项目的，大概是5月底的版本；崩溃在这里：EXC_BAD_ACCESS； ![1663749548621](https://user-images.githubusercontent.com/2683784/191457556-f107b788-425d-4a82-b072-ac6b00327eb3.jpg)

那一行提示什么？EXC_BAD_ACCESS就只有这个吗

**Comment by graceydb** [comment]
@wwmz 
![1663808894821](https://user-images.githubusercontent.com/2683784/191636536-5c345ecc-9889-4fc9-8cfd-7cc6ea59b086.jpg)

**Comment by graceydb** [comment]
这是操作步骤
https://user-images.githubusercontent.com/2683784/191637415-ecf4e875-15ba-4c3f-a985-6f5ef1fb2870.mp4

**Comment by wwmz** [comment]
好的下版本修复 你可以那里加个类型判断 防止崩溃



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yoon ***@***.***&gt;
发送时间: 2022年9月22日 09:09
收件人: wwmz/WMZPageController ***@***.***&gt;
抄送: WMZ ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [wwmz/WMZPageController] WMZPageView KVO 崩溃 (Issue #99)





 
@wwmz

**Comment by wwmz** [comment]
> 好的下版本修复 你可以那里加个类型判断 防止崩溃 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yoon ***@***.***&gt; 发送时间: 2022年9月22日 09:09 收件人: wwmz/WMZPageController ***@***.***&gt; 抄送: WMZ ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [wwmz/WMZPageController] WMZPageView KVO 崩溃 (Issue #99) @wwmz — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


> @wwmz ![1663808894821](https://user-images.githubusercontent.com/2683784/191636536-5c345ecc-9889-4fc9-8cfd-7cc6ea59b086.jpg)

更

> [WMZPageView observeValueForKeyPath:ofObject:change:context:] 要崩溃，崩溃概率很大，一直没找到是什么操作导致的； 而且嵌套的滚动视图实现了getMyScrollView协议之后，偶尔也会出现到顶之后还可以向下滑动的问题

更新一下版本 看看还会不会
